src/backend/interfaces/REST/py.server/caliopen_api/user/authentication.py
fix a bug that prevent application to respond with 403 code if auth cache has expired
=> api authentication does not crash if auth token has expired

doc/api/README.md
documentation is rarely useless
=> Document how to generate single swagger.json from definitions

src/frontend/web_application/.eslintrc, src/frontend/web_application/package.json, src/frontend/web_application/src/components/Button/index.spec.jsx, src/frontend/web_application/src/components/ContactProfile/index.spec.js, src/frontend/web_application/src/components/form/SelectFieldGroup/index.spec.jsx, src/frontend/web_application/src/components/form/TextFieldGroup/index.spec.jsx, src/frontend/web_application/src/components/form/TextareaFieldGroup/index.spec.jsx
Greetings,
this is a following of #89 somehow, where the linting was producing errors on global Jasmine calls.
Jasmine has been removed from Jest, so it's a good idea to start migrating now.
References:
> As part of our effort to remove Jasmine incrementally within Jest, replacing all Jasmine matchers was almost completed.
> We finished the migration of Jasmine assertions to the new Jest matchers
https://facebook.github.io/jest/blog/
I grabbed to occasion to updrade the Jest dependency as well.
=> Remove global Jasmine calls in unit tests

src/frontend/web_application/src/components/SignupForm/index.jsx, src/frontend/web_application/src/components/SignupForm/style.scss, src/frontend/web_application/src/components/form/FieldErrors/style.scss, src/frontend/web_application/src/components/form/FormGrid/index.jsx, src/frontend/web_application/src/components/form/FormGrid/style.scss, src/frontend/web_application/src/components/form/InputText/index.jsx, src/frontend/web_application/src/components/form/TextFieldGroup/style.scss, src/frontend/web_application/src/styles/base/reset.scss, src/frontend/web_application/src/styles/config/config.scss
This removes bottom margins for inputs (bottomSpace = false) and create new prop for FormColumn component (bottomSpace). Now bottom margins are optional for both inputs and columns, so we can choose to apply bottomSpace to containers instead of items.
Updated FieldErrors to fit the fix.
=> Fix spacings

src/frontend/web_application/src/components/form/FieldErrors/style.scss, src/frontend/web_application/src/components/form/InputText/style.scss, src/frontend/web_application/stories/CHANGELOG.md
+ no uppercase for error messages
+ replace red background for input by a border
OLD -> NEW
=> fix form errors UX

src/backend/configs/caliopen-go-api_dev.yaml
Proposal to change backend's REST API listening port from 3141 to 31415, as 3141 is a (old) referenced port instead of 31415 which is free..
=> change backend's REST API listening port from 3141 to 31415.

src/backend/configs/caliopen-api.development.ini, src/backend/configs/caliopen-api.development.ini.sample, src/backend/interfaces/REST/go.server/api_server.go, src/backend/interfaces/REST/go.server/middlewares/authentication.go
The middleware checks authorizations into the running Redis.
Values stored in Redis by python.kvs are now in JSON instead of pickles codec.
=> Add auth middleware to the go.server. 

src/backend/defs/rest-api/paths/discussions.yaml, src/backend/main/py.main/caliopen_main/discussion/store/discussion_index.py
This permit pagination on GET /discussions route, at least for 200 first ones.
This is not a correct fix, as I don't find the way to paginate with a bucket aggregration query on elasticsearch, may it's not possible :/
=> Ugly fix to permit discussion pagination, related to issue #185

src/backend/interfaces/REST/go.server/cmd/caliopen_rest/cli_cmds/root.go
usage :
caliopen_rest -V
caliopen_rest --version
caliopen_rest version
Version number is now a constant : __version__ = "xx.xx.xx"
=> Add version printer to caliopen_rest cli

devtools/docker-compose.yml, src/backend/configs/caliopen-docker.yaml, src/backend/configs/caliopen.yaml.template, src/backend/tools/py.CLI/caliopen_cli/commands/import_email.py
fix #243 
PS: totally blind fix since, Dockerfile cannot add the fix to its workspace
=> fix broker hostname for docker environment in CLI

src/frontend/web_application/src/components/Dropdown/index.jsx
this add `left` to oneOf[..] `position` propType for DropDown (on ReplyForm and MessageList, it opens on left)
=> Fix Dropdown prop `position` propType

src/frontend/web_application/src/scenes/ContactBook/presenter.jsx
`TagList` in `ContactBook` component didn't load tags properly on page refresh, this fixes it.
=> Fix Taglist loading on page refresh

src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
=> do not send 'message.type' on draft creation

src/frontend/web_application/src/components/Link/index.jsx
Set `href` propType to `string` instead of `bool`
=> Fix error in Link PropTypes

src/backend/Dockerfile.py-api
=> Missing caliopen pgp python components for apiv1

devtools/README.md, doc/for-developers/golang-dev.md
A minimal documentation to setup a golang environment for Caliopen development
=> Add a specific documentation for golang development

devtools/docker-compose.yml, src/backend/main/go.backends/index/elasticsearch/elasticsearch.go, src/backend/main/go.backends/index/elasticsearch/messages.go, src/backend/vendor/vendor.json
Reverts CaliOpen/Caliopen#337
@iamdey and @myleneb have same problem using ES5: https://pastebin.com/tri1bqFG
I didn't find easily where is the problem and how to solve it, doing revert for further investigation /w blocking anyone
=> Revert "Upgrade stack to use Elasticsearch v5.4.1 (ie. current version)."

src/backend/main/py.main/caliopen_main/user/store/__init__.py, src/backend/main/py.main/caliopen_main/user/store/user.py, src/backend/tools/py.CLI/caliopen_cli/commands/dump_model.py
Cleanup completly no more used model user counters, as they are deprecated in cassandra and not supported at all by scylladb.
=> Remove all references to user Counter model

CHANGELOG.md, src/backend/defs/rest-api/objects/NewSocialIdentity.yaml, src/backend/main/py.main/caliopen_main/common/objects/base.py, src/backend/main/py.main/caliopen_main/contact/parameters.py, src/backend/main/py.main/caliopen_main/message/objects/message.py, src/backend/main/py.main/caliopen_main/message/parameters/draft.py, src/backend/main/py.main/caliopen_main/message/parameters/message.py, src/backend/main/py.main/caliopen_main/user/parameters/device.py, src/backend/main/py.main/caliopen_main/user/parameters/identity.py, src/backend/main/py.main/caliopen_main/user/parameters/user.py
+ we do not rely anymore exclusively on swagger to validate in&out json docs, but make always use of objects' Schematics json_model.
+ consequently, "required" property of our json_models has been partially removed to permit the validation of partial docs.
+ fix issue #447
=> API always validates ingress & egress json docs against our json_models

devtools/run-tests.sh, src/backend/components/py.pi/caliopen_pi/features/importance_level.py, src/backend/components/py.pi/caliopen_pi/features/mail.py, src/backend/components/py.pi/caliopen_pi/qualifier.py, src/backend/components/py.pi/caliopen_pi/tests/test_importance_level.py, src/backend/components/py.pi/caliopen_pi/tests/test_spam.py
First compute of importance level for an inbound message.
Only simple conditions are implemented regarding all those defined in https://pad.caliopen.org/p/importance
=> Compute inbound importance level, v0

src/backend/configs/caliopen-docker.yaml, src/backend/configs/caliopen.yaml.template, src/backend/main/py.storage/caliopen_storage/helpers/connection.py
Using scylladb we must use protocol_version = 3 to avoid some warning (and automatic downgrade of protocol by python driver).
This pull request permit to define the protocol_version in yaml configuration file
=> Make cassandra protocol_version configurable for python services

devtools/make_release
Add the swagger.json in the dist/<version> repository. This file is needed during deployment for both apiv1 and api2 (and will be deployed as /etc/caliopen/swagger.json)
=> Copy swagger.json into release directory

src/frontend/web_application/src/layouts/Page/components/CallToAction/components/ActionButton/index.jsx, src/frontend/web_application/src/layouts/Page/components/CallToAction/index.jsx, src/frontend/web_application/src/layouts/Page/components/CallToAction/index.spec.jsx, src/frontend/web_application/src/layouts/Page/components/CallToAction/presenter.jsx, src/frontend/web_application/src/scenes/Timeline/components/MessageItem/style.scss, src/frontend/web_application/test/functional/features/22-compose-spec.js, src/frontend/web_application/test/functional/features/40-new-contact-spec.js
- no more principalActionSelector: all actions are stored in
availableActionsSelector
- display same call-to-action on every page (ComposeButton,
CreateContactButton)
- hide ComposeContactButton and ReplyButton
=> Hot fix call-to-action

src/backend/defs/go-objects/message.go
for ancestors_ids to frontend.
=> Always output an empty array instead of 'null' 

src/backend/defs/go-objects/contact.go, src/backend/defs/go-objects/message.go, src/backend/defs/go-objects/participant.go, src/backend/defs/go-objects/public_key.go, src/backend/defs/go-objects/user.go
fix errors when unmarshalling empty nested struct in go-objects in : 
* [lmtp]
* [caliopen_rest]
=> Not try to unmarshal nil map if nested objects are empty.

src/backend/configs/caliopen-docker.yaml, src/backend/configs/caliopen.yaml.template, src/backend/main/py.main/caliopen_main/user/core/user.py
Define a system.max_users configuration key and then API will refuse to create another user if this limit is reached
=> Limit the number of users that can be created 

CHANGELOG.md, src/frontend/web_application/src/components/form/InputText/index.jsx, src/frontend/web_application/src/components/form/TextFieldGroup/index.jsx, src/frontend/web_application/src/scenes/Signin/components/SigninForm/presenter.jsx
this checks if inputs' values are changing after component did mount (ex. if browser auto-fills fields).
- also refactor InputText in order to pass `ref` prop.
Fix https://github.com/CaliOpen/Caliopen/issues/611
=> Get inputs' values when browser autofills fields

src/backend/components/py.pi/caliopen_pi/features/mail.py, src/backend/components/py.pi/caliopen_pi/qualifiers/mail.py, src/backend/configs/caliopen-docker.yaml, src/backend/configs/caliopen.yaml.template, src/backend/main/py.main/caliopen_main/user/core/setups.py
A first tag CALIOPEN will appear automatically on incoming message from a sender defined in configuration file (hosted domains).
This should help validate UX/UI around tag display
=> Add a CALIOPEN tag on inbound message that are from an internal domain sender

src/frontend/web_application/src/styles/base/reset.scss
Fix https://github.com/CaliOpen/Caliopen/issues/722 "[Firefox] adding contact info should have no error on pristine field"
=> Disable pseudo-classes automatically applied to `invalid` inputs

src/backend/interfaces/REST/py.server/caliopen_api/user/user.py, src/backend/main/py.main/caliopen_main/device/core.py
As spooted by @sapiens-sapide , user can have many 'default' devices with previous logic.
Only the first one is named default, others will be named 'new device <device_type>'
=> Only the first device is named default

src/frontend/web_application/src/scenes/MessageList/components/Message/presenter.jsx
Fix https://github.com/CaliOpen/Caliopen/issues/858 to mark message as read on scroll on `Message`
=> Fix onVisibilityChange function on Message

src/frontend/web_application/src/modules/draftMessage/components/AttachmentManager/style.scss, src/frontend/web_application/src/modules/draftMessage/components/NewDraftForm/presenter.jsx, src/frontend/web_application/src/modules/draftMessage/components/NewDraftForm/style.scss, src/frontend/web_application/src/modules/draftMessage/components/ReplyForm/presenter.jsx, src/frontend/web_application/src/modules/draftMessage/components/ReplyForm/style.scss, src/frontend/web_application/src/styles/object/o-clickable.scss
This make default button's style bold and blue (according to UI)
- also fix #851 by re-styling 'send' button on draft.
- also hides rich text editor's button for alpha.
=> Bright default style for Button 

src/frontend/web_application/src/modules/avatar/components/AvatarLetterWrapper/index.jsx, src/frontend/web_application/src/scenes/SearchResults/components/ContactResultItem/presenter.jsx
- Since latest dependencies update,  some styles are upside-down, specifically: avatars are displayed as squares whereas they should appear as circles.
- According to UI, avatars in every scenes are round-shape so:
-> this puts `true` as default value for `isRound` property in `AvatarLetterWrapper` and et voilà it's fixed.
=> Round avatars

src/frontend/web_application/src/components/Badge/index.jsx, src/frontend/web_application/src/components/Badge/style.scss, src/frontend/web_application/src/modules/draftMessage/components/Recipient/presenter.jsx, src/frontend/web_application/src/modules/tags/components/TagItem/index.jsx, src/frontend/web_application/src/modules/tags/components/TagItem/index.spec.jsx, src/frontend/web_application/src/modules/tags/components/TagItem/style.scss
Related to https://trello.com/c/cUX2hgMt/40-bouton-dans-les-badges-sont-trop-petits-sur-mobile
On small badges, buttons are now more easily touchable for mobile users (larger font size + more padding). It also fix style consistency on buttons in `Badge` component.
- adds `onDelete`, `isLoading` and `ariaLabel` props on Badge component
- fix `Badge` and `TagItem` styles
- updates badges on `Recipient` and `TagItem`
before:
after:
=> Fix Badge button width and style

src/frontend/web_application/src/layouts/Page/components/Header/components/SearchField/style.scss, src/frontend/web_application/src/layouts/Page/components/Header/style.scss
Makes search field larger with no animation on medium and large screens. Keeps animated width on small screens.
=> Fix search bar width

src/frontend/web_application/src/modules/tags/components/TagsForm/style.scss
This makes `TagsForm` width fixed to avoid `Modal` to resize while adding or removing tags.
=> Fix TagsForm width

CHANGELOG.md, src/frontend/web_application/src/scenes/MessageList/components/ReplyForm/index.js, src/frontend/web_application/src/store/modules/draft-message.js, src/frontend/web_application/src/store/modules/draft-message.spec.js
=> rewrite draft sync to make sure only readonly message props  are set

src/frontend/web_application/config/server.default.js, src/frontend/web_application/config/server.env-var.js, src/frontend/web_application/server/logger/index.js
syslog is disabled by default
start with the following (or in conf file) to enable it:
```
CALIOPEN_ENABLE_SYSLOG=true bin/server
```
=> add option to enable syslog

src/frontend/web_application/src/components/Modal/index.jsx
With Confirm the Modal is instanciated at runtime on server side, the static function ReactModal.setAppElement uses "document" directly, so it should be used on componentDidMount
=> fix rendering server side with a modal

src/backend/defs/go-objects/identities.go, src/backend/defs/rest-api/objects/RemoteIdentity.yaml, src/backend/doc/api/swagger.json, src/backend/interfaces/REST/go.server/api_server.go, src/backend/interfaces/REST/go.server/operations/identities/identities.go, src/backend/main/go.backends/IdentitiesInterface.go, src/backend/main/go.backends/store/cassandra/identities.go, src/backend/main/go.main/facilities/REST/RESTfacility.go, src/backend/main/go.main/facilities/REST/identities.go, src/backend/main/py.main/caliopen_main/user/store/user.py
Remote Identities have now a property `UUID` that is a primary key, instead of former `identifier`
=> Update models and interfaces to get rid of `identifier`

src/frontend/web_application/src/scenes/RemoteIdentitySettings/components/RemoteIdentityEmail/index.jsx
this caused identity to be polled as new every time an update was done
+ fix bad name to get the active value. previsouly a new remote wasn't enabled by default
=> fix bad props overwriting for remote.info

src/backend/components/py.pgp/setup.py, src/backend/components/py.pi/requirements.deps, src/backend/components/py.pi/setup.py, src/backend/interfaces/NATS/py.client/requirements.deps, src/backend/interfaces/NATS/py.client/setup.py, src/backend/interfaces/REST/py.server/requirements.deps, src/backend/interfaces/REST/py.server/setup.py, src/backend/main/py.main/requirements.deps, src/backend/main/py.main/setup.py, src/backend/tools/py.CLI/requirements.deps, src/backend/tools/py.CLI/setup.py
Drone pipeline startup need a simple information for detection.
Caliopen python package dependencies are stored in a requirements.deps file to be able to do such detection without installing packages
=> Caliopen python dependencies are described in requirements.deps file

src/frontend/web_application/Dockerfile
it reduces frontend image size from about 1GB
```
caliopen_frontend       latest              f1c2fa38cdd4        About a minute ago   659MB
devtools_frontend       latest              cba2ad8dd586        2 months ago         1.61GB
```
=> use multi-stage build in frontend Dockerfile

devtools/docker-compose.yml
caliopen_go actually not a service but a base image for go containers
it is already build by drone and pulled by docker directly on registry
+ remove "image" property. the only purpose was to simplified image name build on dev environment
this can be misunderstood because the property is mainly used to pull latest images from docker hub
also this might bring some conflicts in the eventual publish of Caliopen images on docker hub
=> remove caliopen_go service

CHANGELOG.md, src/frontend/web_application/src/services/message/index.js
Copy messages array to prevent accidental discussion reversal.
=> Fix chronological order in discussion

CHANGELOG.md, src/frontend/web_application/src/modules/message/actions/requestDiscussion.js, src/frontend/web_application/src/scenes/Discussion/components/Message/index.js, src/frontend/web_application/src/scenes/Discussion/components/MessageList/presenter.jsx
force fetch last messages
I forgot my own pattern: 
* `request<Resource>` force fetch to get up to date data and store it to redux (network first strategy)
* `get<Resource>` cache first strategy
* `fetch<Resource>`may be not related to redux (like password related requests)
Well, the best would be to write down this to a rfc.
=> fix last message not visible

CHANGELOG.md, src/frontend/web_application/config/client.default.js, src/frontend/web_application/server/ssr/ssr-middleware.js, src/frontend/web_application/src/components/PageTitle/index.jsx, src/frontend/web_application/src/components/PageTitle/presenter.jsx, src/frontend/web_application/src/scenes/Signup/components/SignupForm/presenter.jsx, src/frontend/web_application/src/services/config.js
Pass env vars to client, strip "alpha.caliopen.org" from client code. One ref remains in tests, but has no incidence on client.
=> Strip hardcoded values

CHANGELOG.md, src/backend/components/py.pi/caliopen_pi/features/mail.py
There is no RFC for this format but it sound the default format using Thunderbird PGP plugin.
This method is imperfect but for a simple mail with a PGP message in it's plain body we should detect correctly encrption.
Should fix #1309
=> Dead simple detection of pgp inline format

CHANGELOG.md, src/frontend/web_application/package.json, src/frontend/web_application/src/scenes/Discussion/components/InstantMessage/index.jsx, src/frontend/web_application/src/scenes/Discussion/components/MailMessage/index.jsx, src/frontend/web_application/yarn.lock
This simple proposal uses ~https://github.com/alexcorvi/anchorme.js/tree/gh-pages/src~ linkifyjs to add clickable links to plain text messages. 
Could be used to make custom intern `mailto` links with some additions.
=> Clickable links in messages

src/backend/components/py.pi/caliopen_pi/features/mail.py, src/backend/components/py.pi/caliopen_pi/tests/fixtures/pgp_crypted_1.eml, src/backend/components/py.pi/caliopen_pi/tests/test_features.py, src/backend/main/py.main/caliopen_main/message/parsers/mail.py, src/backend/main/py.main/caliopen_main/tests/parsers/test_mail.py
Add an _extra_parameters dict to MailMessage parser, when detecting a part of `application/pgp-encrypted` content-type do not produce an attachement but set `encryption` _extra_parameters key to related encryption type.
=> Previous commit remove ability to detect pgp encryption

src/backend/configs/apiv2.yaml, src/backend/defs/go-objects/configs.go, src/backend/interfaces/REST/go.server/api_server.go, src/backend/main/go.main/facilities/Messaging/facility.go
Subscriber model is a one to many and do not permit to scale apiv2 without processing notifications many time.
=> Notifier must use nats Queue subscriber model

CHANGELOG.md, src/frontend/web_application/src/modules/draftMessage/components/DraftMessage/presenter.jsx
https://feedback.caliopen.org/t/erreur-lors-dun-envoi-de-message-vide-comme-une-bouteille-a-la-mer/688
=> disable the send button on quick draft when body is empty

CHANGELOG.md, src/frontend/web_application/src/services/asciify.js, src/frontend/web_application/src/services/asciify.spec.js, src/frontend/web_application/src/services/contact/index.js, src/frontend/web_application/src/services/contact/index.spec.js
=> remove diacritics on first letter on grouped contact

CHANGELOG.md, src/frontend/web_application/src/modules/draftMessage/components/DraftMessage/presenter.jsx
Change send button icon on advanced draft form for a more legible one (and consistent with quick draft) :
This is nothing, but it keeped bothering me for some time.
=> Change send button icon

CHANGELOG.md, src/frontend/web_application/package.json, src/frontend/web_application/server/auth/lib/cookie.js, src/frontend/web_application/server/auth/router/signin.js, src/frontend/web_application/webpack/webpack.config.browser.js
it must use same configuration as res.cookie
+ add new dev helper, start:hostname script to make `caliopen.local` available
but using this, ServiceWorker won't be activated since it requires SSL
fix #1427
=> fix clearCookie

CHANGELOG.md, src/frontend/web_application/src/modules/routing/components/RoutingProvider.jsx, src/frontend/web_application/webpack/webpack.config.browser.js
The service worker did render a cached page (/) when signout instead of the redirect of express server
+ remove the signout route in app and leave the job to the express server
=> compat offline plugin and ssr

CHANGELOG.md, src/backend/main/go.backends/index/elasticsearch/discussions.go
the sub aggregate term `discussion_id.keyword` might have been added by mistake
cf. 800388c47
=> [backend] fix empty discussion list
