CaliOpen/Caliopen

- src/backend/interfaces/REST/py.server/caliopen_api/user/authentication.py
Try to solve a minima the issue #21 
Authentication error message should be enhanced
> When token not found, raise correctly

- src/backend/components/py.pgp/CHANGES.rst
- src/backend/components/py.pgp/MANIFEST.in
- src/backend/components/py.pgp/README.rst
- src/backend/components/py.pgp/caliopen_pgp/__init__.py
- src/backend/components/py.pgp/caliopen_pgp/keys/__init__.py
- src/backend/components/py.pgp/caliopen_pgp/keys/base.py
- src/backend/components/py.pgp/caliopen_pgp/keys/discoverer.py
- src/backend/components/py.pgp/caliopen_pgp/keys/hkp.py
- src/backend/components/py.pgp/caliopen_pgp/keys/keybase.py
- src/backend/components/py.pgp/caliopen_pgp/keys/rfc7929.py
- src/backend/components/py.pgp/setup.cfg
- src/backend/components/py.pgp/setup.py
@sapiens-sapide is it ok for you as component structure ?
it's related to previous work: https://trello.com/c/Jxx1Y2iR/272-api-keys-discovery-basics
> Python package for PGP management in backend

- devtools/Vagrantfile
Expose storage services port outside of vagrant vm, permit more development scenarios
> Expose all services port outside of the vagrant box

- devtools/bootstrap-debian.sh
make use of nodejs6.x and related npm in the vagrant VM
> Install nodejs 6.x version and install the frontend application

- src/backend/configs/caliopen-api.development.ini
- src/backend/configs/caliopen-api.development.ini.sample
- src/backend/interfaces/REST/py.server/caliopen_api/user/user.py
set ttl for authentication to 24h for development convenience
> set ttl for authentication to 24h for development convenience

- src/backend/interfaces/REST/py.server/caliopen_api/user/contact.py
return expected response on route /contacts with method POST
> return expected response on route /contacts with method POST

- devtools/README.md
- devtools/Vagrantfile
- devtools/bootstrap-debian.sh
- src/frontend/web_application/package.json
+ configure frontend to run into a vagrant box
> Add a start script for the frontend to the Vagrantfile

- doc/api/swagger.json
- src/backend/interfaces/REST/py.server/caliopen_api/message/message.py
- src/backend/main/py.main/caliopen_main/message/core/raw.py
route `/raws/` crashed the application if ressource was not found. Now, returns a 404
> fix incorrect `ressource not found` handling

- devtools/README.md
- devtools/setup-virtualenv.sh
- doc/for-developers/README.md
Some documentation enhancements, always useful
> Various fixes

- src/frontend/web_application/src/scenes/ContactList/components/ContactItem/index.jsx
- src/frontend/web_application/src/scenes/ContactList/index.jsx
- src/frontend/web_application/src/scenes/ContactList/style.scss
import raw code from angular app, all necessary code should be present to build contact list page
> WIP: migrate contact list from angularjs app

- .travis.yml
- devtools/run-tests.sh
Using git diff on ../src/backend and ../src/frontend to start testing for both components may permit to start having a conditional CI using travis.
@iamdey WDYT ? and if agree can you define frontend testing a minima (not using a functional API for the moment)
> Start a CI using travis with attempt to test for backend and frontend only if needed

- devtools/run-tests.sh
- src/frontend/web_application/src/components/Button/index.jsx
- src/frontend/web_application/src/components/Button/style.scss
- src/frontend/web_application/src/components/Link/index.jsx
- src/frontend/web_application/src/components/Link/style.scss
- src/frontend/web_application/src/components/Page/components/NavigationAlt/presenter.jsx
- src/frontend/web_application/src/components/Spinner/style.scss
- src/frontend/web_application/src/styles/object/o-clickable.scss
> Frontend cliackable active

- doc/api/swagger.json
- src/backend/defs/rest-api/objects/Contact.json
- src/backend/defs/rest-api/objects/Discussion.json
- src/backend/defs/rest-api/objects/NewPublicKey.json
- src/backend/defs/rest-api/objects/PublicKey.json
- src/backend/defs/rest-api/objects/User.json
- src/backend/defs/rest-api/paths/raws.json
- src/backend/defs/rest-api/swagger-root.json
- src/backend/main/py.main/caliopen_main/message/core/thread.py
- src/backend/main/py.main/caliopen_main/message/store/discussion_index.py
fix datetime type bug in discussion serialization
fix incorrect swagger definition for route raws/{raw_msg_id}
> fix datetime type bug in discussion serialization + swagger definition

- doc/api/swagger.json
- src/backend/defs/rest-api/objects/Contact.json
- src/backend/defs/rest-api/objects/Discussion.json
- src/backend/defs/rest-api/objects/Message.json
- src/backend/defs/rest-api/objects/NewPublicKey.json
- src/backend/defs/rest-api/objects/PublicKey.json
- src/backend/defs/rest-api/objects/User.json
- src/backend/main/py.main/caliopen_main/message/parameters.py
- src/backend/main/py.main/caliopen_main/user/parameters/contact.py
- src/backend/main/py.main/caliopen_main/user/parameters/user.py
enforce ISO8601/RFC3339 for date-time strings returned by API
> enforce ISO8601/RFC3339 for date-time strings returned by API

- src/frontend/web_application/.storybook/webpack.config.js
- src/frontend/web_application/src/components/Icon/index.jsx
- src/frontend/web_application/src/components/Icon/index.spec.jsx
- src/frontend/web_application/src/components/Icon/style.scss
- src/frontend/web_application/src/components/Page/style.scss
- src/frontend/web_application/src/components/Spinner/index.jsx
- src/frontend/web_application/src/components/Spinner/index.spec.jsx
- src/frontend/web_application/src/components/Subtitle/index.spec.jsx
- src/frontend/web_application/src/components/TextList/components/ItemContent/index.jsx
- src/frontend/web_application/src/components/TextList/index.jsx
- src/frontend/web_application/src/components/TextList/index.spec.jsx
- src/frontend/web_application/src/components/TextList/style.scss
- src/frontend/web_application/src/styles/vendor/bootstrap_font-awesome.scss
- src/frontend/web_application/stories/Welcome.jsx
- src/frontend/web_application/stories/components/Icon.jsx
- src/frontend/web_application/stories/components/Spinner.jsx
- src/frontend/web_application/stories/components/Subtitle.jsx
- src/frontend/web_application/stories/components/TextList.jsx
- src/frontend/web_application/stories/index.jsx
- src/frontend/web_application/stories/presenters/ComponentWrapper.jsx
* spinner
* subtitle
* icon 
* text list
> Frontend components

- src/frontend/web_application/.eslintrc
1 - Remove redundant config keys 
Most of this is already set by the Airbnb config, and some is outdated.
We'd better let this project maintain that kind of things.
See:
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/es6.js  
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/index.js
2 - Add the `root` key
There's a small performance gain as ESLint won't climb the file system tree to find potential other configs to merge in. Also safer.
See:
http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy
> Simplify ESLint config

- devtools/README.md
- devtools/docker-compose.yml
- src/backend/interfaces/REST/py.server/Dockerfile
- src/backend/tools/py.CLI/Dockerfile
+ fix docker import command (& doc)
> Prevent using cache when cloning in Dockerfile

- src/frontend/web_application/src/components/LoginForm/index.jsx
- src/frontend/web_application/src/components/LoginForm/style.scss
- src/frontend/web_application/src/layouts/AuthPage/index.jsx
- src/frontend/web_application/src/layouts/AuthPage/style.scss
Make `<LoginForm>` and `<AuthPage>` fit the UI
> Front/ <LoginForm> and <AuthPage> styles

- doc/RFCs/username_specifications.md
proposal for the username format rules and validation.
> proposal for the username format rules and validation.

- devtools/bootstrap-debian.sh
- devtools/docker-compose.yml
- src/backend/interfaces/REST/go.server/Dockerfile
- src/backend/interfaces/REST/go.server/caliopen-api.docker.yaml
Permit to build the apiv2 container and use it in a complete docker stack.
Vagrant update started but not yet achieved
> Dockerize apiv2

- doc/api/swagger.json
- src/backend/defs/rest-api/objects/User.json
- src/backend/main/py.main/caliopen_main/objects/email.py
- src/backend/main/py.main/caliopen_main/user/parameters/contact.py
fix response server on route /me (was not compliant to swagger definition).
> fix response server on route /me (was not compliant to swagger definition).

- devtools/README.md
- src/frontend/web_application/server/auth/router/signup.js
+ improve docker documentation
> Add missing recovery_email param

- src/frontend/web_application/src/components/Page/components/Header/components/UserMenu/presenter.jsx
- src/frontend/web_application/src/components/Page/components/Header/components/UserMenu/presenter.spec.jsx
- src/frontend/web_application/src/components/Page/components/Header/index.jsx
- src/frontend/web_application/src/components/Page/components/NavigationAlt/presenter.jsx
- src/frontend/web_application/src/components/Page/components/NavigationAlt/presenter.spec.jsx
+ use user.name instead of user.contact.title
+ remove old hardcoded isAuthenticaed check
> fix usermenu when no contact is associated

- src/frontend/web_application/.storybook/webpack.config.js
- src/frontend/web_application/stories/CHANGELOG.md
- src/frontend/web_application/stories/components/Dropdown.jsx
- src/frontend/web_application/stories/index.jsx
use full control mode for storybook webpack config
> Add Dropdown to storybook

- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/components/SigninForm/presenter.jsx
- src/frontend/web_application/src/components/SignupForm/presenter.jsx
> Add navigation links between signin and signup

- src/frontend/web_application/src/layouts/Page/components/Navigation/components/StickyNavBar/index.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/index.jsx
It also adds a little css animation on the navbar on scroll wich was present on previous poc
> Migrate StickyNavBar component

- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/components/form/CollectionFieldGroup/components/AddFieldGroup/index.jsx
- src/frontend/web_application/src/components/form/CollectionFieldGroup/components/AddFieldGroup/style.scss
- src/frontend/web_application/src/components/form/CollectionFieldGroup/components/DeleteFieldGroup/index.jsx
- src/frontend/web_application/src/components/form/CollectionFieldGroup/components/DeleteFieldGroup/style.scss
- src/frontend/web_application/src/components/form/CollectionFieldGroup/index.js
- src/frontend/web_application/src/components/form/CollectionFieldGroup/presenter.jsx
- src/frontend/web_application/src/components/form/CollectionFieldGroup/style.scss
- src/frontend/web_application/src/components/form/index.js
- src/frontend/web_application/stories/CHANGELOG.md
- src/frontend/web_application/stories/components/CollectionFieldGroup.jsx
- src/frontend/web_application/stories/index.jsx
Refactor multiple ip from device form into a CollectionFieldGroup component
> Add CollectionFieldGroup component

- src/frontend/web_application/server/error/middlewares/catch-error.js
+ use status from err
+ test accept json before anything else to render error
> fix render errror from frontend web server

- doc/api/swagger.json
- src/backend/defs/rest-api/objects/DeviceLocation.json
- src/backend/defs/rest-api/objects/NewDevice.json
- src/backend/interfaces/REST/py.server/caliopen_api/user/device.py
- src/backend/main/py.main/caliopen_main/objects/base.py
- src/backend/main/py.main/caliopen_main/objects/device.py
- src/backend/main/py.main/caliopen_main/user/core/__init__.py
- src/backend/main/py.main/caliopen_main/user/core/device.py
- src/backend/main/py.main/caliopen_main/user/parameters/__init__.py
- src/backend/main/py.main/caliopen_main/user/parameters/device.py
- src/backend/main/py.main/caliopen_main/user/store/device.py
Add PATCH /devices/<device_id> method.
locations (list of network addresses) related to a device are also managed
> [wip]Feature/backend/device patch

- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/components/TagsForm/components/TagItem/index.jsx
- src/frontend/web_application/src/components/TagsForm/components/TagItem/index.spec.jsx
- src/frontend/web_application/src/components/TagsForm/components/TagItem/style.scss
- src/frontend/web_application/src/components/TagsForm/components/TagSearch/index.jsx
- src/frontend/web_application/src/components/TagsForm/components/TagSearch/index.spec.jsx
- src/frontend/web_application/src/components/TagsForm/presenter.jsx
- src/frontend/web_application/src/components/TagsForm/presenter.spec.jsx
- src/frontend/web_application/src/layouts/Settings/presenter.jsx
- src/frontend/web_application/src/routes.jsx
- src/frontend/web_application/src/scenes/Tags/index.js
- src/frontend/web_application/src/scenes/Tags/presenter.jsx
- src/frontend/web_application/src/services/api-patch/index.js
- src/frontend/web_application/src/services/api-patch/index.spec.js
- src/frontend/web_application/src/store/configure-store.js
- src/frontend/web_application/src/store/middlewares/crash-reporter-middleware.js
- src/frontend/web_application/src/store/middlewares/promise-middleware.js
- src/frontend/web_application/src/store/middlewares/tags-middleware.js
- src/frontend/web_application/src/store/middlewares/thunk-middleware.js
- src/frontend/web_application/src/store/modules/tag.js
- src/frontend/web_application/src/store/reducer.js
> implement tags management in settings

- src/backend/protocols/py.smtp/caliopen_smtp/agent.py
- src/backend/tools/py.CLI/caliopen_cli/commands/import_email.py
with current db models (local identity & raw messages)
> cli-import (re)works 

- devtools/docker-compose.yml
- src/backend/interfaces/REST/go.server/Dockerfile
change port # for REST API into docker & docker-compose conf files.
> change port # for REST API into docker & docker-compose conf files.

- src/backend/interfaces/REST/py.server/caliopen_api/message/message.py
- src/backend/main/py.main/caliopen_main/message/core/raw.py
- src/backend/main/py.storage/caliopen_storage/core/base.py
fix how raw msg requests are handled backend side to conform to new db model.
> fix how raw msg requests are handled backend side to conform to new db model.

- src/frontend/web_application/package.json
- src/frontend/web_application/src/components/DiscussionDraft/index.jsx
- src/frontend/web_application/src/components/DiscussionDraft/index.spec.jsx
- src/frontend/web_application/src/components/DiscussionTextarea/index.jsx
- src/frontend/web_application/src/components/DiscussionTextarea/index.spec.jsx
- src/frontend/web_application/src/components/ReplyForm/index.js
- src/frontend/web_application/src/components/ReplyForm/presenter.jsx
- src/frontend/web_application/src/components/ReplyForm/presenter.spec.jsx
- src/frontend/web_application/stories/components/Reply.jsx
- src/frontend/web_application/stories/index.jsx
> ReplyForm & DiscussionDraft components architecture

- CONTRIBUTING.md
> update contributor list

- src/frontend/web_application/src/components/ContactAvatarLetter/index.jsx
- src/frontend/web_application/src/components/ContactAvatarLetter/style.scss
- src/frontend/web_application/src/components/DiscussionTextarea/style.scss
- src/frontend/web_application/src/components/MessageList/components/DayMessageList/style.scss
- src/frontend/web_application/src/components/MessageList/components/Message/index.jsx
- src/frontend/web_application/src/components/MessageList/components/Message/style.scss
- src/frontend/web_application/src/components/MessageList/components/MessageActionsContainer/index.jsx
- src/frontend/web_application/src/components/MessageList/components/MessageActionsContainer/style.scss
- src/frontend/web_application/src/components/MessageList/presenter.jsx
- src/frontend/web_application/src/components/MessageList/style.scss
- src/frontend/web_application/src/components/ReplyForm/presenter.jsx
- src/frontend/web_application/src/components/ReplyForm/style.scss
- src/frontend/web_application/src/styles/config/theme/dark.scss
- src/frontend/web_application/src/styles/object/o-avatar.scss
- src/frontend/web_application/src/styles/object/o-form-element.scss
- src/frontend/web_application/src/styles/vendor/foundation-sites/_config.scss
- view < 380px
-- doesn't show avatars
-- fixed position for ReplyForm
-- Icon Buttons
- 380px < view < 640px
-- show small avatars
-- static position for ReplyForm
-- Icon Buttons
- view > 640px
-- show medium avatars
-- Text and Icon Buttons
- still missing responsive menu for bottom actions in ReplyForm
- also, waiting for Button refactor, buttons are hacked with span to simulate Icon only buttons and buttons' colors are not fixed yet
> Frontend/fixes/ Responsive ReplyForm and MessageList

- src/backend/protocols/go.smtp/vendor/vendor.json
should fix issue #224 and depreciates PR #222
> fix incorrect dependency references for go.smtp

- src/backend/interfaces/NATS/py.client/caliopen_nats/subscribers.py
Add a more 'pythonic' way of building the json strings for nats messages.
> Refactor the way nats message string are build in caliopen_nats

- src/backend/tools/py.CLI/caliopen_cli/commands/import_vcard.py
Add several NewContact at a user with several vcard in the same file
> import vcard with several vcard on a file

- devtools/docker-compose.yml
- src/backend/interfaces/REST/go.server/caliopen-api.docker.yaml
Api will start correctly in a docker container with this configuration
> Link correctly for docker usage of API

- src/backend/tools/py.CLI/caliopen_cli/commands/import_email.py
Using bad raw data, nothing to parse, participants is the way we discover this problem
> At least participants were missing when parsing a mail message

- devtools/api-mock/messages/index.js
- src/frontend/web_application/src/scenes/MessageList/index.js
- src/frontend/web_application/src/scenes/MessageList/presenter.jsx
- src/frontend/web_application/src/store/modules/message.js
> use actions api instead of PATCH to update message is_unread

- devtools/api-mock/discussions/index.js
- devtools/api-mock/messages/index.js
- src/frontend/web_application/src/components/MessageList/components/Message/index.jsx
- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
- src/frontend/web_application/src/store/modules/discussion.js
> revert calc participants from discussion

- devtools/api-mock/discussions/index.js
- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
- src/frontend/web_application/src/store/modules/discussion.js
> fix handling invalid api answer for discussion & add subject to draft

- src/frontend/web_application/src/components/Badge/index.jsx
- src/frontend/web_application/src/components/BlockList/index.jsx
- src/frontend/web_application/src/components/Button/index.jsx
- src/frontend/web_application/src/components/ContactAvatarLetter/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/AddressDetails/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/EmailDetails/index.jsx
> refactor proptypes

- src/frontend/web_application/src/layouts/Page/components/Navigation/style.scss
this fixes https://github.com/CaliOpen/Caliopen/issues/296 "page goes behind on scroll"
> Fix Navigation height

- src/frontend/web_application/src/scenes/Signup/index.js
> fix missing redirect after signup

- src/frontend/web_application/src/components/Link/index.jsx
- src/frontend/web_application/src/layouts/Page/components/Header/components/UserMenu/presenter.jsx
add href property to Link in order to prevent usage of react-router's Link
fix #300
> fix signout should reset client store

- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/App.jsx
- src/frontend/web_application/src/components/Icon/index.jsx
- src/frontend/web_application/src/routes.jsx
- src/frontend/web_application/src/scenes/AppRoute/index.jsx
- src/frontend/web_application/src/scenes/Auth/index.jsx
- src/frontend/web_application/src/services/i18n.js
- src/frontend/web_application/src/store/middlewares/tabs-middleware.js
- src/frontend/web_application/src/store/modules/tab.js
+ create or update tab
+ load translator in memory for re-use
> implement tab for settings

- src/backend/brokers/go.emails/broker.go
- src/backend/brokers/go.emails/inbound.go
- src/backend/brokers/go.emails/outbound.go
- src/backend/configs/caliopen-go-api_dev.yaml
- src/backend/interfaces/REST/go.server/api_server.go
- src/backend/interfaces/REST/go.server/cmd/caliopen_rest/cli_cmds/serve.go
- src/backend/interfaces/REST/go.server/middlewares/authentication.go
- src/backend/interfaces/REST/go.server/middlewares/swagger.go
- src/backend/interfaces/REST/go.server/operations/messages/actions.go
- src/backend/interfaces/REST/go.server/operations/users/identities.go
- src/backend/interfaces/REST/go.server/operations/users/user.go
- src/backend/interfaces/REST/go.server/operations/users/username.go
- src/backend/main/go.backends/store/cassandra/messages.go
- src/backend/main/go.main/RESTfacility.go
- src/backend/protocols/go.smtp/receiver.go
- src/backend/protocols/go.smtp/submitter.go
+ go-api enforces swagger inbound validation.
+ go-api "send" operation correctly responds errors to frontend.
> Feature/backend/go api/swagger error handling

- src/backend/main/py.main/caliopen_main/message/core/raw.py
- src/backend/tools/py.CLI/caliopen_cli/commands/import_email.py
fix #316 using existing column naming for raw_message
> Naming column as it should not be, but will make import work

- devtools/docker-compose.yml
- src/backend/Dockerfile.message_handler
- src/backend/Dockerfile.py-api
> Remove 'volumes' instruction in docker-compose for apiv1.

- src/frontend/web_application/src/services/i18n.js
* fix an error thrown in IE & Edge
fix #350
> make sure languages is an array

- src/backend/defs/rest-api/objects/NewRemoteIdentity.yaml
- src/backend/defs/rest-api/paths/identities.yaml
- src/backend/defs/rest-api/swagger-root.yaml
- src/backend/doc/api/swagger.json
- src/backend/interfaces/REST/py.server/caliopen_api/user/user.py
- src/backend/main/py.main/caliopen_main/user/core/user.py
- src/backend/main/py.main/caliopen_main/user/parameters/__init__.py
- src/backend/main/py.main/caliopen_main/user/parameters/identity.py
- src/backend/main/py.main/caliopen_main/user/store/user.py
Rework RemoteIdentity to an usable form for fetching an IMAP source.
Make a basic API to create a remote identity for an user.
> [wip]Feature/backend/prepare remote identities

- src/backend/defs/rest-api/paths/imports.yaml
- src/backend/doc/api/swagger.json
Add parameters in imports.yaml.
Generate a new swagger after add parameters to import vcards.
> Feature/backend/defs/rest api/paths/imports.yaml/fix

- src/frontend/web_application/src/components/ContactProfile/index.jsx
This bug prevented to display Contact page.
> Fix bug on contact.tags in ContactProfile

- CHANGELOG.md
- src/backend/interfaces/NATS/py.client/caliopen_nats/__init__.py
- src/backend/interfaces/REST/go.server/cmd/caliopen_rest/cli_cmds/root.go
- src/backend/interfaces/REST/py.server/caliopen_api/__init__.py
- src/backend/main/py.main/caliopen_main/__init__.py
- src/backend/main/py.storage/caliopen_storage/__init__.py
- src/backend/protocols/go.smtp/cmd/caliopen_lmtpd/cli_cmds/root.go
- src/backend/tools/py.CLI/caliopen_cli/__init__.py
- src/frontend/web_application/package.json
Bump packages version to 0.2.0 to match release numbering to come (tag on master with devtools/make_release script)
Add a draft for a CHANGELOG.
@iamdey I need your help for client features and others
> Release/prepare 0.2

- devtools/README.md
- devtools/docker-compose.staging.yml
* ports will not be published on host
* frontend (4000) and broker (2525) are publihed to 127.0.0.1
* add doc for production scenarios
fix: #386
> add docker-compose configuration for production

- src/frontend/web_application/src/scenes/Account/index.js
- src/frontend/web_application/src/scenes/Account/presenter.jsx
- src/frontend/web_application/src/store/modules/contact.js
+ allow user's contact edtion
+ remoteIdenties not yet connected, cf. settings story
> connect Account to user

- src/frontend/web_application/src/components/ContactProfile/components/ContactProfileForm/index.jsx
+ refactor handle method
fix #394
> fix contact's birthday input form

- src/backend/brokers/go.emails/config.go
- src/backend/brokers/go.emails/email.go
- src/backend/brokers/go.emails/inbound.go
- src/backend/main/go.backends/LDAInterfaces.go
- src/backend/main/go.backends/store/cassandra/raw_messages.go
+ func takes a RawMessage object as param instead of a string.
> Change go/store/cassandra StoreRawMessage() signature.

- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/package.json
- src/frontend/web_application/src/components/ContactDetails/components/AddressForm/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/AddressForm/style.scss
- install react-country-region-selector
- update styles
- update locales
> Add country and region selectors

- src/frontend/web_application/src/components/Dropdown/index.jsx
as you can't pass custom props to `<div>`, you have to list them before `...props`
> Fix `Unknown props` error on Dropdown

- src/frontend/web_application/src/components/MessageList/components/Message/presenter.jsx
> render html message body

- CHANGELOG.md
- src/frontend/web_application/src/components/NewDraftForm/presenter.jsx
- src/frontend/web_application/src/components/NewDraftForm/style.scss
- src/frontend/web_application/src/components/RecipientsList/components/Recipient/presenter.jsx
- src/frontend/web_application/src/components/form/TextFieldGroup/index.jsx
- src/frontend/web_application/src/components/form/TextFieldGroup/style.scss
> add subject to compose & inline modifier in input field group

- CHANGELOG.md
- src/frontend/web_application/locales/fr/main.json
> fix bad wording for update message failure

- CHANGELOG.md
- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/scenes/Contact/index.js
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
- src/frontend/web_application/src/store/modules/contact.js
cf. #424 
---
hope this will not conflict w/ your current dev @myleneb. Let's merge yours before.
> catch contact update failure & refactor Contact component

- devtools/api-mock/all.fixture.js
- devtools/api-mock/participants/data.json
- devtools/api-mock/participants/index.js
- src/frontend/web_application/src/components/NewDraftForm/presenter.jsx
- src/frontend/web_application/src/components/RecipientsList/index.js
- src/frontend/web_application/src/components/RecipientsList/presenter.jsx
- src/frontend/web_application/src/components/RecipientsList/presenter.spec.jsx
- src/frontend/web_application/src/store/modules/draft-message.js
- src/frontend/web_application/src/store/modules/participant-suggestions.js
- src/frontend/web_application/src/store/reducer.js
- src/frontend/web_application/test/functional/features/22-compose-spec.js
+ add TAB support for better UX when moving between inputs
> use suggest api instead of contact filter

- src/backend/defs/rest-api/objects/NewMessageV2.yaml
- src/backend/doc/api/swagger.json
- src/backend/interfaces/REST/py.server/caliopen_api/base/exception.py
- src/backend/interfaces/REST/py.server/caliopen_api/message/message.py
- src/backend/main/py.main/caliopen_main/message/objects/message.py
- src/backend/main/py.main/caliopen_main/message/parameters/draft.py
by request from iamdey in PR #436
> Feature/backend/frontend can post draftID

- src/frontend/web_application/src/scenes/MessageList/components/DraftForm/presenter.jsx
- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
refactor participants selection in createDraft when user requesting a new draft instead of before posting to api
> participants was always empty when creating draft

- src/frontend/web_application/src/scenes/MessageList/index.js
- src/frontend/web_application/src/scenes/MessageList/presenter.jsx
- src/frontend/web_application/src/store/middlewares/messages-middleware.js
- src/frontend/web_application/src/store/modules/message.js
- src/frontend/web_application/src/store/modules/message.spec.js
refactor the way messages of a discussion is invalidated and refetched
> fetch message list in an infinit loop due to bad condition

- src/frontend/web_application/src/components/ContactDetails/components/AddressForm/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/AddressForm/style.scss
- src/frontend/web_application/src/components/ContactDetails/components/BirthdayDetails/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/EmailForm/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/EmailForm/style.scss
- src/frontend/web_application/src/components/ContactDetails/components/FormButton/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/FormButton/style.scss
- src/frontend/web_application/src/components/ContactDetails/components/FormSelector/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/FormSelector/style.scss
- src/frontend/web_application/src/components/ContactDetails/components/IdentityForm/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/IdentityForm/style.scss
- src/frontend/web_application/src/components/ContactDetails/components/ImForm/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/ImForm/style.scss
- src/frontend/web_application/src/components/ContactDetails/components/OrgaForm/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/OrgaForm/style.scss
- src/frontend/web_application/src/components/ContactDetails/components/PhoneForm/index.jsx
- src/frontend/web_application/src/components/ContactDetails/components/PhoneForm/style.scss
- src/frontend/web_application/src/components/ContactDetails/index.jsx
- src/frontend/web_application/src/scenes/Contact/style.scss
These are styles for forms in ContactDetails components.
(see captures: https://tree.taiga.io/project/caliopen-caliopen/task/382?kanban-status=815893)
> Styles for forms on ContactDetails

- src/backend/main/py.main/caliopen_main/contact/objects/contact.py
- src/backend/main/py.main/caliopen_main/user/core/user.py
for issue #341 mentionned in PR #389
> Add 'title' to Contact related to an user (user creation context).

- src/frontend/web_application/src/components/Device/components/DeviceForm/presenter.jsx
- src/frontend/web_application/src/components/SigninForm/presenter.jsx
- src/frontend/web_application/src/components/SignupForm/presenter.jsx
- src/frontend/web_application/src/components/form/FormGrid/index.jsx
- src/frontend/web_application/src/scenes/SettingsContacts/components/ContactsForm/presenter.jsx
- src/frontend/web_application/src/scenes/SettingsInterface/components/InterfaceForm/presenter.jsx
- src/frontend/web_application/src/scenes/SettingsInterface/components/PresentationForm/presenter.jsx
- src/frontend/web_application/src/scenes/SettingsSignatures/components/SignatureForm/presenter.jsx
- src/frontend/web_application/src/scenes/UserProfile/components/ProfileForm/presenter.jsx
remove form tag from FormGrid: It only is a decorator now
> refactor FormGrid

- src/backend/defs/go-objects/message.go
The `plain_body` field is a boolean to indicate to frontend whether the message's body must be rendered as plain or as html.
> Add `plain_body` boolean field to messages json.

- src/frontend/web_application/src/layouts/Page/components/NavigationAlt/components/TabList/presenter.jsx
- src/frontend/web_application/src/layouts/Page/components/NavigationAlt/presenter.jsx
Add attr `data-toggle` to NavigationAlt links allows to close NavigationAlt on click.
> Add attr `data-toggle` to NavigationAlt links

- src/frontend/web_application/src/layouts/Page/components/Header/presenter.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/index.jsx
- src/frontend/web_application/src/scenes/DiscussionList/components/DiscussionItemActionsContainer/presenter.jsx
fix issue https://github.com/CaliOpen/Caliopen/issues/459: display responsive view consistently for screens < 640px
> Fix responsive view for small screens

- devtools/api-mock/settings/data.json
- src/frontend/web_application/server/ssr/index.js
- src/frontend/web_application/server/ssr/ssr-middleware.js
- src/frontend/web_application/src/App.jsx
- src/frontend/web_application/src/components/I18nProvider/index.js
- src/frontend/web_application/src/components/I18nProvider/presenter.jsx
- src/frontend/web_application/src/components/SettingsProvider/index.js
- src/frontend/web_application/src/components/SettingsProvider/presenter.jsx
- src/frontend/web_application/src/index.jsx
- src/frontend/web_application/src/routes.jsx
- src/frontend/web_application/src/scenes/AppRoute/index.jsx
- src/frontend/web_application/src/scenes/ApplicationSettings/presenter.jsx
- src/frontend/web_application/src/scenes/Auth/index.jsx
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
- src/frontend/web_application/src/scenes/PageNotFound/index.jsx
- src/frontend/web_application/src/services/i18n.js
- src/frontend/web_application/src/services/settings/index.js
- src/frontend/web_application/src/store/middlewares/tabs-middleware.js
- src/frontend/web_application/test/functional/features/30-settings-spec.js
+ add I18nProvider & SettingsProvider
+ add PageNotFound route & Component
> apply i18n from settings, separate locale & language

- src/frontend/web_application/src/scenes/Signup/index.js
- src/frontend/web_application/src/scenes/Signup/presenter.jsx
+ refactor & remove old unused code in signup
> add settings to create user

- CHANGELOG.md
- devtools/api-mock/messages/data.json
- devtools/api-mock/messages/index.js
- src/frontend/web_application/src/components/BlockList/style.scss
- src/frontend/web_application/src/components/InfiniteScroll/index.jsx
- src/frontend/web_application/src/components/MessageList/presenter.jsx
- src/frontend/web_application/src/components/MessageList/style.scss
- src/frontend/web_application/src/routes.jsx
- src/frontend/web_application/src/scenes/MessageList/index.js
- src/frontend/web_application/src/scenes/MessageList/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/AuthorAvatar/index.js
- src/frontend/web_application/src/scenes/Timeline/components/AuthorAvatar/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/AuthorAvatar/style.scss
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/index.js
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/style.scss
- src/frontend/web_application/src/scenes/Timeline/index.js
- src/frontend/web_application/src/scenes/Timeline/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/style.scss
- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
- src/frontend/web_application/src/store/middlewares/messages-middleware.js
- src/frontend/web_application/src/store/modules/message.js
- src/frontend/web_application/src/store/modules/message.spec.js
- src/frontend/web_application/test/functional/features/10_discussion-spec.js
- src/frontend/web_application/test/functional/features/20-message-list-spec.js
- src/frontend/web_application/test/functional/features/21-reply-to-messag-spec.js
- src/frontend/web_application/test/functional/features/22-compose-spec.js
- src/frontend/web_application/test/functional/features/23-delete-message-spec.js
- src/frontend/web_application/test/functional/protractor.conf.js
+ store message collections by type & key
+ sort messages
+ move discussion list to /discussions
+ add load more to message list
+ remove requests to discussions
+ fix #454
> add timeline view

- src/frontend/web_application/src/styles/object/o-form-element.scss
Fix https://github.com/CaliOpen/Caliopen/issues/474
> Fix Select styles

- CHANGELOG.md
- src/frontend/web_application/src/scenes/ContactBook/presenter.jsx
> fix rendering catact.tags when undefined

- src/frontend/web_application/.eslintrc
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/Navbar/components/Tab/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/presenter.jsx
- src/frontend/web_application/src/services/message/index.js
- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
- src/frontend/web_application/src/store/middlewares/tabs-middleware.js
- src/frontend/web_application/src/store/modules/discussion.js
- src/frontend/web_application/src/store/modules/message.js
+ remove discussion requirement from draft and use lastMessage for participant calc
> deprecate discussion actions & render participants in tab

- src/frontend/web_application/src/scenes/MessageList/index.js
- src/frontend/web_application/src/scenes/MessageList/presenter.jsx
> dicsussion tab should not close if there is a draft saved

- src/frontend/web_application/src/components/RecipientList/index.js
- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
- src/frontend/web_application/src/store/modules/draft-message.js
> remove calc participants in draft from message in reply

- src/frontend/web_application/src/components/RecipientList/index.js
- src/frontend/web_application/src/components/RecipientList/presenter.jsx
- src/frontend/web_application/src/components/RecipientList/style.scss
- src/frontend/web_application/src/services/settings/index.js
- src/frontend/web_application/src/services/settings/withSettings.jsx
- src/frontend/web_application/src/store/configure-store.js
- src/frontend/web_application/src/store/middlewares/participant-suggestions-middleware.js
- src/frontend/web_application/src/store/middlewares/participant-suggestions-middleware.spec.js
- src/frontend/web_application/src/store/modules/participant-suggestions.js
> consolidate participant suggestions w/ contact

- CHANGELOG.md
- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/components/Dropdown/index.jsx
- src/frontend/web_application/src/components/Dropdown/services/getOffset/index.jsx
- src/frontend/web_application/src/components/Dropdown/style.scss
- src/frontend/web_application/src/components/MessageList/components/Message/presenter.jsx
- src/frontend/web_application/src/components/MultidimensionalPi/presenter.jsx
- src/frontend/web_application/src/components/NewDraftForm/presenter.jsx
- src/frontend/web_application/src/components/RecipientList/presenter.jsx
- src/frontend/web_application/src/components/RecipientList/style.scss
- src/frontend/web_application/src/components/ReplyForm/presenter.jsx
- src/frontend/web_application/src/layouts/Page/components/Header/components/UserMenu/presenter.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/ApplicationSwitcher/presenter.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/ApplicationSwitcher/style.scss
- src/frontend/web_application/src/layouts/Page/components/Navigation/index.jsx
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageItemContainer/presenter.jsx
- src/frontend/web_application/src/styles/vendor/bootstrap_foundation-sites.scss
- update components using Dropdown
- replace DropdowMenu with isMenu props on Dropdown
- remove foundation's  Dropdown export
> Refacto Dropdown

- src/backend/main/py.main/caliopen_main/user/parameters/settings.py
> fix typo in `contact_display_format` choices

- CHANGELOG.md
- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/hoc/notification.jsx
- src/frontend/web_application/src/hoc/settings.jsx
- src/frontend/web_application/src/layouts/Page/components/CallToAction/components/ComposeContactButton/index.js
- src/frontend/web_application/src/layouts/Page/components/CallToAction/components/ReplyButton/index.js
- src/frontend/web_application/src/scenes/ApplicationSettings/index.jsx
- src/frontend/web_application/src/scenes/Contact/components/ContactTitleField/index.js
- src/frontend/web_application/src/scenes/Contact/index.js
- src/frontend/web_application/src/scenes/ContactBook/components/ContactItem/index.js
- src/frontend/web_application/src/scenes/ContactBook/components/ContactList/index.js
- src/frontend/web_application/src/scenes/ContactBook/components/ImportContact/index.js
- src/frontend/web_application/src/scenes/NewDraft/index.js
- src/frontend/web_application/src/scenes/SettingsIdentities/index.js
- src/frontend/web_application/src/scenes/Signup/index.js
- src/frontend/web_application/src/services/settings/index.js
- src/frontend/web_application/src/store/configure-store.js
- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
- src/frontend/web_application/src/store/middlewares/participant-suggestions-middleware.js
- src/frontend/web_application/src/store/selectors/settings.js
settings and with notification
> refactor hoc and selectors and notify draft saved

- CHANGELOG.md
- src/frontend/web_application/server/app.js
- src/frontend/web_application/src/scenes/MessageList/components/DraftForm/index.js
- src/frontend/web_application/src/store/configure-store.js
this makes react-redux-scroll limited to browser build target
fix #549
> render SSR by default + fix accessing window for SSR

- CHANGELOG.md
- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/components/DraftMessageActionsContainer/index.js
- src/frontend/web_application/src/components/DraftMessageActionsContainer/presenter.jsx
- src/frontend/web_application/src/components/DraftMessageActionsContainer/style.scss
- src/frontend/web_application/src/components/NewDraftForm/presenter.jsx
- src/frontend/web_application/src/components/ReplyForm/presenter.jsx
- src/frontend/web_application/src/components/ReplyForm/presenter.spec.jsx
- src/frontend/web_application/src/scenes/MessageList/components/DraftForm/index.js
- src/frontend/web_application/src/scenes/MessageList/components/DraftForm/presenter.jsx
- src/frontend/web_application/src/scenes/NewDraft/index.js
- src/frontend/web_application/src/scenes/NewDraft/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/style.scss
- src/frontend/web_application/src/scenes/Timeline/components/MessageItemContainer/index.js
- src/frontend/web_application/src/scenes/Timeline/components/MessageItemContainer/presenter.jsx
- src/frontend/web_application/src/styles/object/o-clickable.scss
+ add prefix for draft in timeline
> bind delete message in timeline and delete draft

- src/frontend/web_application/README.md
- src/frontend/web_application/config/client.default.js
- src/frontend/web_application/package.json
- src/frontend/web_application/server/index.js
- src/frontend/web_application/server/ssr/ssr-middleware.js
- src/frontend/web_application/src/index.jsx
arg is now bin/server --config=<path>
> make piwik siteId configurable & change bin/server arg

- src/frontend/web_application/src/layouts/Page/components/Header/presenter.jsx
The usage of this Component is commented, so I thought that I should also coment its definition in order to prevent the linting error.
> Fix Linting Error

- src/frontend/web_application/package.json
- src/frontend/web_application/src/scenes/MessageList/components/DraftForm/index.js
- src/frontend/web_application/src/store/configure-store.js
- src/frontend/web_application/yarn.lock
> Upgrade react-redux-scroll

- src/frontend/web_application/server/auth/lib/redirect.js
- src/frontend/web_application/server/auth/router/signin.js
- src/frontend/web_application/server/auth/router/signup.js
new config application was missing in this part of server
+ refactor the error handling in case api doesn't allow to authenticate right after signup
> fix error after signup

- CHANGELOG.md
- src/frontend/web_application/src/components/MessageList/components/Message/presenter.jsx
- src/frontend/web_application/src/components/MessageList/services/groupMessages/index.js
- src/frontend/web_application/src/components/MessageList/services/groupMessages/index.spec.js
> use date_insert to sort message in discussion

- src/frontend/web_application/src/components/MessageList/components/Message/index.js
- src/frontend/web_application/src/components/MessageList/components/Message/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageDate/index.js
- src/frontend/web_application/src/scenes/Timeline/components/MessageDate/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/index.js
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/presenter.jsx
- src/frontend/web_application/test/functional/features/10_discussion-spec.js
+ select locale from settings in Timeline & discussion
fix #567
> consistent usage of react-moment in Timeline

- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
- src/frontend/web_application/src/store/modules/draft-message.js
> sync draft after update & force sync readOnly dynamic props

- src/frontend/web_application/src/scenes/Contact/index.js
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
Fix https://github.com/CaliOpen/Caliopen/issues/571
> Add handleCancel function

- src/backend/brokers/go.emails/email.go
- src/backend/main/go.backends/LDAInterfaces.go
- src/backend/main/go.backends/store/cassandra/discussions.go
- src/backend/main/go.backends/store/cassandra/tags.go
…after sending a brand new email.
> Fix issue #566 : create discussion lookup 

- src/backend/defs/go-objects/external_references.go
- src/backend/defs/go-objects/message.go
- src/backend/defs/go-objects/participant.go
> Fix typos and errors when unmarshalling Go message object

- src/backend/interfaces/REST/go.server/operations/contacts/Identities.go
- src/backend/interfaces/REST/go.server/operations/helpers.go
- src/backend/interfaces/REST/go.server/operations/messages/actions.go
- src/backend/interfaces/REST/go.server/operations/messages/attachments.go
- src/backend/interfaces/REST/go.server/operations/messages/messages.go
- src/backend/interfaces/REST/go.server/operations/tags/tags.go
- src/backend/interfaces/REST/go.server/operations/users/user.go
after this PR, apiv2 will immediately returns a 422 error if uuids string provided in param are invalid.
> Enforce uuid strings normalization on apiv2 routes.

- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/components/SignupForm/presenter.jsx
- src/frontend/web_application/src/components/SignupForm/style.scss
fix #609
- Alpha wording
- preview of `[username]@alpha.caliopen.org` under username field
- Hide TOS checkbox
> Alpha wording on Signup

- src/frontend/web_application/src/components/Dropdown/index.jsx
- src/frontend/web_application/src/components/InfiniteScroll/index.jsx
- src/frontend/web_application/src/components/RecipientList/presenter.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/Navbar/components/HorizontalScroll/index.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/StickyNavBar/index.jsx
- src/frontend/web_application/src/services/event-manager/index.js
- src/frontend/web_application/test/functional/features/22-compose-spec.js
add an event manager for scroll, resize, click ...
in order to manage globals into (document/window) and allow mock
cf. #632
> refactor document event

- CHANGELOG.md
- src/frontend/web_application/src/components/Dropdown/index.jsx
- src/frontend/web_application/src/components/InfiniteScroll/index.jsx
- src/frontend/web_application/src/components/RecipientList/presenter.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/Navbar/components/HorizontalScroll/index.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/StickyNavBar/index.jsx
- src/frontend/web_application/src/services/event-manager/index.js
- src/frontend/web_application/test/functional/features/22-compose-spec.js
+ event prevent default when backspace is pressed when editing a recipient
+ handle comma and semicolon to add a recipient
fix #581 
fix #603
> handle blur on recipient list in a draft

- src/frontend/web_application/src/scenes/SearchResults/components/ContactResultItem/presenter.jsx
- src/frontend/web_application/src/scenes/SearchResults/components/Highlights/index.jsx
- src/frontend/web_application/src/scenes/SearchResults/components/Highlights/index.spec.jsx
- src/frontend/web_application/src/scenes/SearchResults/components/MessageResultItem/presenter.jsx
+ support multiple search terms
+ render highlights in contacts
> explode highlights using regexp

- src/frontend/web_application/src/scenes/UserSecurity/components/PasswordForm/index.jsx
fix https://github.com/CaliOpen/Caliopen/issues/642
> Fix handleSubmit in PasswordForm

- CHANGELOG.md
- src/backend/main/go.backends/store/cassandra/users.go
- src/backend/main/go.main/users/password.go
missed the password_strength property within `store.UpdateUserPasswordHash` func.
> Also save updated password_strength when saving a new password.

- CHANGELOG.md
- src/frontend/web_application/src/scenes/UserSecurity/components/LoginDetails/index.jsx
- src/frontend/web_application/src/scenes/UserSecurity/components/PasswordDetails/index.jsx
When you tried to access user/security directly via browser bar, you got an error.
this fix this bug.
> Fix UserSecurity

- CHANGELOG.md
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
- src/frontend/web_application/src/scenes/ContactBook/components/ContactItem/presenter.jsx
- src/frontend/web_application/src/store/middlewares/tabs-middleware.js
Keep consistency of contact's name (and avatar letter) in ContactBook, Contact and tab.label
> Contact's name consistency

- CHANGELOG.md
- src/frontend/web_application/src/components/NewDraftForm/presenter.jsx
- src/frontend/web_application/src/components/ReplyForm/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/components/DraftForm/presenter.jsx
- src/frontend/web_application/src/scenes/NewDraft/presenter.jsx
- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
> add spinner and disable button send

- CHANGELOG.md
- src/frontend/web_application/src/components/MessageList/components/Message/presenter.jsx
- src/frontend/web_application/src/components/MessageList/components/MessageActionsContainer/index.jsx
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
- src/frontend/web_application/src/scenes/ContactBook/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/components/DraftForm/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/presenter.jsx
- src/frontend/web_application/src/scenes/NewDraft/presenter.jsx
- src/frontend/web_application/src/scenes/PageNotFound/index.jsx
- src/frontend/web_application/src/scenes/SearchResults/presenter.jsx
- src/frontend/web_application/src/scenes/SettingsRoute/index.jsx
- src/frontend/web_application/src/scenes/Timeline/presenter.jsx
- src/frontend/web_application/src/scenes/UserRoute/index.jsx
on FF on poc: open 2 conversations, close in same order
reopen last conversation, it will render 2 tabs of the same conversation
> disable buggy scrollspy

- CHANGELOG.md
- src/frontend/web_application/src/components/RecipientList/presenter.jsx
while loading new suggestions, the dropdown is forced to closed, it should not
fix: #664
> remove unexpected behaviour which make dropdown to force close

- CHANGELOG.md
- src/frontend/web_application/src/scenes/Contact/index.js
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
cf. #668
this is a split of commit 845b6e6 with no delete button on user's contact page
> refactor prevent delete user's contact

- src/frontend/web_application/package.json
- src/frontend/web_application/server/ssr/ssr-middleware.js
- src/frontend/web_application/src/App.jsx
- src/frontend/web_application/src/components/PageTitle/index.jsx
- src/frontend/web_application/src/components/PageTitle/presenter.jsx
- src/frontend/web_application/src/hoc/tab.js
- src/frontend/web_application/src/scenes/ApplicationSettings/presenter.jsx
- src/frontend/web_application/src/scenes/Contact/index.js
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
- src/frontend/web_application/src/scenes/ContactBook/index.jsx
- src/frontend/web_application/src/scenes/ContactBook/presenter.jsx
- src/frontend/web_application/src/scenes/Devices/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/index.js
- src/frontend/web_application/src/scenes/MessageList/presenter.jsx
- src/frontend/web_application/src/scenes/PageNotFound/index.jsx
- src/frontend/web_application/src/scenes/SearchResults/presenter.jsx
- src/frontend/web_application/src/scenes/SettingsIdentities/presenter.jsx
- src/frontend/web_application/src/scenes/SettingsSignatures/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/presenter.jsx
- src/frontend/web_application/src/scenes/UserPrivacy/presenter.jsx
- src/frontend/web_application/src/scenes/UserProfile/presenter.jsx
- src/frontend/web_application/src/scenes/UserSecurity/presenter.jsx
- src/frontend/web_application/template/index.ejs
- src/frontend/web_application/yarn.lock
Fix   https://github.com/CaliOpen/Caliopen/issues/597
> add document title on scenes

- CHANGELOG.md
- src/frontend/web_application/locales/en/main.json
- src/frontend/web_application/locales/fr/main.json
- src/frontend/web_application/locales/template/main.json
- src/frontend/web_application/src/scenes/Contact/index.js
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
+ invalidate contacts on deletion
+ add notification on error
> handle activity in contact (fetch/save/delete)

- src/frontend/web_application/src/index.jsx
this method is preconized by react w/ ReactDOMServer https://reactjs.org/docs/react-dom.html#hydrate
> use hydrate instead of render

- CHANGELOG.md
- src/frontend/web_application/src/scenes/MessageList/components/DraftForm/index.js
- src/frontend/web_application/src/store/middlewares/draft-messages-middleware.js
+ fix show correctly parent message in reply usingi the draft in edition instead saved draft
fix #616
> do not save draft when body nor participant are empty

- CHANGELOG.md
- src/frontend/web_application/src/scenes/MessageList/components/DraftForm/index.js
- src/frontend/web_application/src/scenes/MessageList/index.js
- src/frontend/web_application/src/scenes/Timeline/components/MessageItemContainer/index.js
- src/frontend/web_application/src/store/modules/message.js
- src/frontend/web_application/src/store/selectors/message.js
+ on the Timeline the draft wasn't effectively invalidated
+ the draft selector was not correct and showed a deleted draft
and so add message's collection selector
> fix delete a draft

- CHANGELOG.md
- src/frontend/web_application/src/scenes/ApplicationSettings/index.jsx
> cast notification_delay_disappear in integer

- CHANGELOG.md
- src/frontend/web_application/config/client.default.js
- src/frontend/web_application/config/server.default.js
- src/frontend/web_application/config/server.env-var.js
- src/frontend/web_application/server/api/index.js
- src/frontend/web_application/src/scenes/ContactBook/components/ImportContactForm/presenter.jsx
> Add config entry for max body size of a request

- CHANGELOG.md
- src/frontend/web_application/src/store/middlewares/participant-suggestions-middleware.js
> fix suggest when contact has no emails

- CHANGELOG.md
- src/frontend/web_application/src/layouts/Page/components/NavigationAlt/presenter.jsx
> use href for signout instead of react router

- src/backend/defs/rest-api/paths/users.yaml
- src/backend/doc/api/swagger.json
- src/backend/interfaces/REST/py.server/caliopen_api/base/exception.py
- src/backend/interfaces/REST/py.server/caliopen_api/user/imports.py
- src/backend/interfaces/REST/py.server/caliopen_api/user/user.py
- src/backend/main/py.main/caliopen_main/user/core/user.py
+ must be a valid email address
+ must be unique
+ domain must be outside of instance's domains
Will prevent issue #673 to happen.
> Validate recovery_email provided at user creation.

- src/frontend/web_application/src/scenes/Timeline/presenter.jsx
- src/frontend/web_application/src/store/modules/message.js
> filter param was missing if timeline has been invalidated

- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/presenter.jsx
> display date_insert for draft

- src/frontend/web_application/src/scenes/SearchResults/components/ContactResultItem/presenter.jsx
- src/frontend/web_application/src/scenes/SearchResults/components/MessageResultItem/presenter.jsx
> handle null for highlights in search results

- src/frontend/web_application/src/scenes/UserSecurity/components/PasswordForm/index.jsx
This fixes a bug related to i18n on PasswordForm
> withI18n in PasswordForm

- src/frontend/web_application/src/modules/tags/actions/createTag/index.js
> following last spec: only label is allowed on tag creation

- CHANGELOG.md
- src/frontend/web_application/src/modules/user/index.js
- src/frontend/web_application/src/modules/user/services/usernameNormalizer/index.js
- src/frontend/web_application/src/scenes/Signin/components/SigninForm/presenter.jsx
- src/frontend/web_application/src/scenes/Signin/presenter.jsx
(useful for mobile devices)
fix #655
> trim username before signin

- src/frontend/web_application/src/components/TagsForm/presenter.jsx
- src/frontend/web_application/src/modules/tags/actions/createTag/index.js
> handle create tag error in entity's tags management

- src/frontend/web_application/src/components/Badge/style.scss
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageItem/style.scss
- src/frontend/web_application/src/scenes/Timeline/components/MessageSelector/index.jsx
- src/frontend/web_application/src/scenes/Timeline/index.js
- src/frontend/web_application/src/scenes/Timeline/presenter.jsx
Add edit tags and delete message functions (not yet implemented for multiple messages) on `Timeline`
> Add edit tag/delete message functions

- src/backend/interfaces/REST/py.server/caliopen_api/user/contact.py
Hotfix applied to alpha platform to permit contact creation
> Only if tags are not empty refuse to create contact

- devtools/migrations/index_migration_v2_to_v3.py
Adjust index migration script to run better
> [wip]The script can run many times without recreate v3 index each time

- src/frontend/web_application/src/scenes/Contact/index.js
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/components/Message/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageSelector/index.jsx
- src/frontend/web_application/src/scenes/Timeline/index.js
- src/frontend/web_application/src/scenes/Timeline/presenter.jsx
- src/frontend/web_application/test/functional/features/60-tag-spec.js
related to previous refactor about updateEntityTags
> update tag management in contact, timeline, messsage-list interfaces

- src/frontend/web_application/src/scenes/Signup/components/SignupForm/presenter.jsx
- src/frontend/web_application/src/scenes/Signup/presenter.jsx
Fix https://github.com/CaliOpen/Caliopen/issues/742
> Disable submit button & add spinner when submitting signup form

- src/frontend/web_application/src/layouts/Page/components/Header/components/SearchField/presenter.jsx
Fix https://github.com/CaliOpen/Caliopen/issues/715
> Prevent submitting search form when term.length < 3

- src/frontend/web_application/locale/de/messages.json
- src/frontend/web_application/locale/en/messages.json
- src/frontend/web_application/locale/fr/messages.json
- src/frontend/web_application/src/scenes/ApplicationSettings/components/NotificationSettings/presenter.jsx
- src/frontend/web_application/src/scenes/ApplicationSettings/index.jsx
- src/frontend/web_application/src/scenes/ApplicationSettings/presenter.jsx
Fix https://github.com/CaliOpen/Caliopen/issues/702
> Add notifications when saving settings

- src/backend/defs/rest-api/objects/NewUser.yaml
- src/backend/doc/api/swagger.json
Missing accepted parameters on user creation, tos and privacy boolean
> Adapt swagger schema to full client payload on user creation

- src/frontend/web_application/src/scenes/SearchResults/components/ContactResultItem/presenter.jsx
- src/frontend/web_application/src/scenes/SearchResults/components/MessageResultItem/presenter.jsx
return null instead of undefined in the render prop
fix #792
> fix search

- README.md
> Correcting a little english error

- CHANGELOG.md
- src/frontend/web_application/package.json
- src/frontend/web_application/src/scenes/ApplicationSettings/components/NotificationSettings/presenter.jsx
- src/frontend/web_application/test/functional/features/10_discussion-spec.js
- src/frontend/web_application/test/functional/features/20-message-list-spec.js
- src/frontend/web_application/test/functional/features/21-reply-to-messag-spec.js
- src/frontend/web_application/test/functional/features/22-compose-spec.js
- src/frontend/web_application/test/functional/features/23-delete-message-spec.js
- src/frontend/web_application/test/functional/features/40-new-contact-spec.js
- src/frontend/web_application/test/functional/features/50-search-spec.js
- src/frontend/web_application/test/functional/features/70-device-spec.js
- src/frontend/web_application/yarn.lock
connected fields in redux-form requires a type to correctly handle value
fix #797
> add type checkbox for connected fields

- CHANGELOG.md
- src/frontend/web_application/src/store/middlewares/messages-middleware.js
> fix timeline filtering: invalidate after sending drafts

- doc/index.md
> try add puml

- src/frontend/web_application/src/scenes/MessageList/components/Message/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/components/Message/style.scss
- src/frontend/web_application/src/scenes/MessageList/components/MessageActionsContainer/index.jsx
- src/frontend/web_application/src/scenes/MessageList/components/MessageActionsContainer/style.scss
- src/frontend/web_application/src/scenes/MessageList/components/MessageAttachments/index.jsx
- src/frontend/web_application/src/scenes/MessageList/components/MessageAttachments/style.scss
- src/frontend/web_application/src/scenes/MessageList/components/MessageList/presenter.jsx
- src/frontend/web_application/src/services/message/index.js
- src/frontend/web_application/src/services/message/index.spec.js
- src/frontend/web_application/test/functional/features/21-reply-to-messag-spec.js
- src/frontend/web_application/test/functional/features/23-delete-message-spec.js
- src/frontend/web_application/test/functional/features/60-tag-spec.js
This is a first pass for bright styles on MessageList
> Bright styles on Message in MessageList

- src/frontend/web_application/src/modules/draftMessage/components/AttachmentManager/presenter.jsx
> disable multiple file upload in draft attachments

- src/frontend/web_application/src/scenes/Signin/components/SigninForm/presenter.jsx
- src/frontend/web_application/src/scenes/Signin/presenter.jsx
+ hide error when changing input
> display general error when signin fails

- CHANGELOG.md
- src/frontend/web_application/src/layouts/Page/style.scss
- src/frontend/web_application/src/modules/a11y/index.js
- src/frontend/web_application/src/modules/a11y/services/tabIndexes.js
- src/frontend/web_application/src/modules/draftMessage/components/DiscussionDraft/index.jsx
- src/frontend/web_application/src/modules/draftMessage/components/NewDraftForm/presenter.jsx
- src/frontend/web_application/src/modules/draftMessage/components/ReplyForm/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/components/MessageList/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/components/MessageList/style.scss
- src/frontend/web_application/src/scenes/MessageList/components/ReplyExcerpt/index.js
- src/frontend/web_application/src/scenes/MessageList/components/ReplyExcerpt/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/components/ReplyExcerpt/style.scss
- src/frontend/web_application/src/scenes/MessageList/components/ReplyForm/index.js
- src/frontend/web_application/src/scenes/MessageList/components/ReplyForm/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/presenter.jsx
- src/frontend/web_application/src/store/modules/draft-message.js
+ refactor DaftForm to ReplyForm
+ use isFetching draft to prevent render loop in DraftForm
+ add basic a11y module
> add an excerpt of draft form in mobile view & toggle w/ form

- CHANGELOG.md
- src/frontend/web_application/src/components/Confirm/index.jsx
- src/frontend/web_application/src/components/Confirm/index.spec.jsx
- src/frontend/web_application/src/components/Confirm/style.scss
- src/frontend/web_application/src/components/index.js
- src/frontend/web_application/src/modules/draftMessage/components/DraftMessageActionsContainer/presenter.jsx
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
- src/frontend/web_application/src/scenes/Contact/style.scss
- src/frontend/web_application/src/scenes/MessageList/components/MessageActionsContainer/index.jsx
- src/frontend/web_application/src/scenes/MessageList/components/MessageActionsContainer/style.scss
- src/frontend/web_application/src/scenes/MessageList/components/MessageList/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/index.js
- src/frontend/web_application/src/scenes/MessageList/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/MessageSelector/index.jsx
- src/frontend/web_application/test/functional/features/23-delete-message-spec.js
> add Confirm component & confirm message & contact deletion

- CHANGELOG.md
- src/frontend/web_application/src/scenes/ContactBook/components/ContactList/presenter.jsx
- src/frontend/web_application/src/services/contact/index.js
> getContactTitle() function to check if contact.title is null

- src/frontend/web_application/webpack/config.js
this prevent to have app before vendor in template
> add sort chunks method in webpack

- src/frontend/web_application/src/hoc/notification.jsx
- src/frontend/web_application/src/layouts/Page/components/NotificationCenter/style.scss
- src/frontend/web_application/src/scenes/MessageList/index.js
- src/frontend/web_application/src/store/middlewares/axios-middleware.js
Fix https://github.com/CaliOpen/Caliopen/issues/860
Adds notifications `customStyles` in `withNotification()` and `notify()`
> Notifications custom styles

- src/frontend/web_application/src/scenes/MessageList/components/Message/style.scss
- src/frontend/web_application/src/scenes/PageNotFound/index.jsx
- src/frontend/web_application/src/scenes/PageNotFound/style.scss
- src/frontend/web_application/src/styles/config/config.scss
This fix styles for unicorn and ASCII logo's in `PageNotFound`
> Unicorn and ASCII logo's styles for PageNotFound

- src/frontend/web_application/src/layouts/Page/components/Header/style.scss
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/Navbar/components/HorizontalScroll/style.scss
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/Navbar/components/NavbarItem/style.scss
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/StickyNavBar/index.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/components/TimelineFilterContainer/presenter.jsx
- src/frontend/web_application/src/layouts/Page/components/Navigation/style.scss
- src/frontend/web_application/src/layouts/Page/presenter.jsx
- src/frontend/web_application/src/layouts/Page/style.scss
- src/frontend/web_application/src/styles/config/config.scss
- src/frontend/web_application/src/styles/object/o-navigation.scss
This smoothly sticks `Navbar` on top when scrolling and enlarges space between header and navigation in order to display coming background image.
> Fix Navbar position

- devtools/api-mock/me/data.json
- devtools/api-mock/me/index.js
- src/frontend/web_application/src/scenes/ResetPassword/components/ResetPasswordForm/presenter.jsx
- src/frontend/web_application/src/scenes/UserSecurity/components/PasswordForm/index.jsx
- src/frontend/web_application/test/functional/features/80-account-spec.js
- src/frontend/web_application/test/functional/utils/user-util.js
> fix import zxcvbn

- src/backend/configs/minio/config.json
this will prevent to minio to update itself this file
which may bring errors in docker environment
**I only push the edited file by minio**, please make sure it still ok.
the following error happen when minio update this file when builing cli Dockerfile for example:
```
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
```
It's due to minio which update itself the file from within a docker container, so the owner becomes root e.g.
```
ls -la src/backend/configs/minio/config.json  
-rw------- 1 root root 2,0K avril 30 16:42 src/backend/configs/minio/config.json
-rw------- 1 root root 2,0K avril 30 16:42 src/backend/configs/minio/config.json.old
```
so docker is unable to build what is in backend directory
> update config file of minio

- src/frontend/web_application/src/layouts/Page/components/ImportanceSliderContainer/style.scss
This fix ImportanceSlider bright styles.
> Fix background color of ImportanceSlider

- src/frontend/web_application/locale/en/messages.json
- src/frontend/web_application/locale/fr/messages.json
- src/frontend/web_application/src/scenes/MessageList/components/Message/presenter.jsx
- src/frontend/web_application/src/scenes/MessageList/components/Message/style.scss
This fixes participant list overflow and ellipsis in `Message`
> Fix participants list text-overflow

- src/frontend/web_application/package.json
- src/frontend/web_application/server/ssr/ssr-middleware.js
- src/frontend/web_application/yarn.lock
Prevent malicious injection that should not happen using Yahoo's JSON seriallzer.
> Safer serialization

- doc/install/frontend-development.md
- src/backend/protocols/go.imap/cmd/imapctl/cli_cmds/addremote.go
- src/backend/protocols/go.imap/cmd/imapctl/cli_cmds/fullfetch.go
- src/backend/protocols/go.imap/cmd/imapctl/cli_cmds/syncremote.go
- src/backend/protocols/go.imap/fetcher.go
- src/backend/protocols/go.imap/imap.go
change the way to invoke imapctl CLI : give a username instead of user_id
> Improvement/backend cli/addremote by username

- src/frontend/web_application/bin/dev-server
- src/frontend/web_application/package.json
- src/frontend/web_application/server/auth/middlewares/check-token.js
- src/frontend/web_application/server/auth/middlewares/decode-cookie.js
- src/frontend/web_application/server/error/middlewares/catch-error.js
- src/frontend/web_application/server/index.js
- src/frontend/web_application/server/logger/index.js
- src/frontend/web_application/webpack/webpack.config.server.js
- src/frontend/web_application/yarn.lock
+ this log into console (colorized) and to a file : combined.log
+ the format is: `${info.timestamp} ${info.level} ${info.label} - ${info.message}`
+ stacktraces have been removed when unecessary but still displayed on stderr (not in combined.log)
> add the logger winston to node server

- src/frontend/web_application/src/modules/draftMessage/components/NewDraftForm/presenter.jsx
> Confirm send if subject or body is empty

- devtools/docker-compose.yml
- src/backend/configs/caliopen-go-lmtp_dev.yaml
inbucket choose to use less surprising ports:
https://github.com/jhillyerd/inbucket/commit/86c8ccf9eaf10bae3989611476bba785440e1dc5#diff-3254677a7917c6c01f55212f86c57fbfR21
> remove unecessary port exposure and fix inbucket' smtp port

- devtools/docker-compose.yml
+ allow to stop one container and replace by native app
+ fix port exposure for apiv1
> loose configuration for docker containers

- devtools/docker-compose.yml
- doc/install/frontend-development.md
update the doc frontend install, but almost ready for any kind of developments
> Add the possibility to build an image

- src/frontend/web_application/src/modules/i18n/components/I18nLoader/index.jsx
- src/frontend/web_application/webpack/webpack.config.server.js
> Pascalduez hotfix/ssr

- src/frontend/web_application/src/scenes/UserProfile/index.js
- src/frontend/web_application/src/scenes/UserProfile/presenter.jsx
- src/frontend/web_application/src/scenes/UserProfile/style.scss
- src/frontend/web_application/src/store/modules/user.js
> Modal confirmation for account deletion

- src/frontend/web_application/src/store/modules/message.js
> make sure the draft is added to all and draft timeline collections

- src/backend/main/py.main/caliopen_main/contact/core.py
> Contact to lookup can not exist anymore, do not raise and deliver

- src/frontend/web_application/src/modules/device/services/signature/index.js
> remove forgotten console.log

- src/frontend/web_application/package.json
- src/frontend/web_application/webpack/config.js
- src/frontend/web_application/webpack/webpack.config.server.js
- src/frontend/web_application/yarn.lock
+ disable OptimizeCssAssetsPlugin on dev mode
+ add HardSourceWebpackPlugin for server build
> optim build time for dev

- src/frontend/web_application/src/components/ParticipantsIconLetter/index.jsx
- src/frontend/web_application/src/components/ParticipantsIconLetter/style.scss
- src/frontend/web_application/src/layouts/Page2/components/Tab/presenter.jsx
- src/frontend/web_application/src/layouts/Page2/components/Tab/style.scss
- src/frontend/web_application/src/modules/avatar/index.js
> add AvatarLetters to discussion tabs

- src/frontend/web_application/src/scenes/Timeline2/index.jsx
- src/frontend/web_application/src/scenes/Timeline2/style.scss
Sticky action bar, displays tags & split avatars in Timeline
> [legacy UI] Sticky action bar, tags, split avatars

- src/frontend/web_application/src/modules/draftMessage/components/ReplyForm/presenter.jsx
> Disable button "Copy To" in reply form

- CHANGELOG.md
- src/frontend/web_application/src/scenes/MessageList/index.js
- src/frontend/web_application/src/services/message/index.js
- src/frontend/web_application/src/store/middlewares/messages-middleware.js
- src/frontend/web_application/src/store/modules/message.js
As for now, fixes incorrect behavior on "load more" in discussions : new messages were appended to bottom of page.
> Fix discussion «load more»

- CHANGELOG.md
- src/frontend/web_application/src/scenes/Timeline/presenter.jsx
> incorrect filter argument for load more

- CHANGELOG.md
- src/frontend/web_application/src/scenes/Signin/components/SigninForm/presenter.jsx
This reverts commit f305e695a3b68c0c7f9d9576a9b0a77f71dce7a2.
> Revert mis-deleted signup & recovery mail links

- src/frontend/web_application/locale/fr/messages.json
- src/frontend/web_application/src/modules/draftMessage/components/DraftMessageActionsContainer/presenter.jsx
- src/frontend/web_application/src/modules/pi/services/pi/index.js
- src/frontend/web_application/src/scenes/Discussion/components/MailMessage/index.jsx
- src/frontend/web_application/src/scenes/Discussion/components/MailMessage/style.scss
- src/frontend/web_application/src/scenes/Discussion/components/Message/index.js
- src/frontend/web_application/src/scenes/Discussion/components/Message/presenter.jsx
- src/frontend/web_application/src/scenes/Discussion/components/MessagePi/index.jsx
- src/frontend/web_application/src/scenes/Discussion/components/MessagePi/style.scss
- src/frontend/web_application/src/scenes/Discussion/presenter.jsx
- src/frontend/web_application/src/scenes/Discussion/style.scss
- src/frontend/web_application/src/scenes/Timeline2/components/DiscussionItem/index.jsx
- src/frontend/web_application/src/scenes/Timeline2/components/DiscussionItem/style.scss
- src/frontend/web_application/src/scenes/Timeline2/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline2/style.scss
- src/frontend/web_application/src/styles/config/theme/light.scss
- Comment out unavailable batch operations
- Fix Reply on Message (still an error in middleware)
- Some CSS corrections/refactor.
> UIv4 Corrections to prepare merge

- src/frontend/web_application/src/modules/scroll/hoc/scrollManager.jsx
- src/frontend/web_application/src/scenes/Discussion/presenter.jsx
Still need to restore scroll properly.``
> Scroll fixes

- src/frontend/web_application/server/app.js
FYI @MonsieurLanza now it should work correctly with
```
yarn start:dev
```
> correctly handle HAS_SSR env var

- src/frontend/web_application/server/ssr/ssr-middleware.js
- src/frontend/web_application/src/components/AppLoader/index.jsx
- src/frontend/web_application/src/index.jsx
- src/frontend/web_application/src/modules/routing/components/AuthenticatedLayout/index.jsx
- src/frontend/web_application/src/modules/routing/components/AuthenticatedLayout/withAuthenticatedProps.jsx
- src/frontend/web_application/src/modules/settings/components/WithSettings/index.js
- src/frontend/web_application/src/modules/settings/components/WithSettings/presenter.jsx
- src/frontend/web_application/src/modules/user/components/WithUser/index.js
- src/frontend/web_application/src/modules/user/components/WithUser/presenter.jsx
- src/frontend/web_application/src/store/modules/settings.js
- src/frontend/web_application/src/store/modules/user.js
+ fix initialization of settings
+ add current location link when something went wrong on app loader
> redirect to signin when user lost authentication

- src/frontend/web_application/package.json
- src/frontend/web_application/yarn.lock
see https://github.com/villadora/express-http-proxy/issues/377
downgrade to working version 1.1.0
master still has a problem
> a bug was introduced in express-http-proxy

- src/frontend/web_application/src/scenes/Timeline2/components/DiscussionItem/index.jsx
- src/frontend/web_application/src/scenes/Timeline2/components/DiscussionItem/style.scss
> switch colors read/unread

- src/frontend/web_application/src/scenes/Contact/components/ImForm/index.jsx
> IM form more permissive

- src/frontend/web_application/src/scenes/ApplicationSettings/components/DesktopNotificationSettings/presenter.jsx
- src/frontend/web_application/src/services/browser-notification/index.js
cf. #1099 
actually notif works except it requires the browser to be on an other tab (not only in background or minimize ... at least on linux)
cf. https://devdocs.io/dom/document/hidden
> force desktop notif for test

- CHANGELOG.md
- devtools/api-mock/messages/data.json
- src/frontend/web_application/src/scenes/Discussion/components/InstantMessage/index.jsx
- src/frontend/web_application/src/scenes/Discussion/components/InstantMessage/style.scss
- src/frontend/web_application/src/scenes/Discussion/components/MailMessage/style.scss
- src/frontend/web_application/src/scenes/Discussion/components/MessagePi/index.jsx
- src/frontend/web_application/src/scenes/Discussion/components/MessagePi/style.scss
More BEM compliant, correct recipients and message from user restyle.
> Refactor of InstantMessage component

- CHANGELOG.md
- src/frontend/web_application/src/modules/draftMessage/components/DraftMessage/presenter.jsx
- src/frontend/web_application/src/modules/draftMessage/services/filterIdentities.js
- src/frontend/web_application/src/modules/draftMessage/services/getIdentityProtocol.js
> refactor getIdentityProtocol to use it in draft validation

- CHANGELOG.md
- src/frontend/web_application/src/scenes/Discussion/components/InstantMessage/index.jsx
- src/frontend/web_application/src/scenes/Discussion/components/MailMessage/index.jsx
- src/frontend/web_application/src/scenes/Discussion/components/Message/presenter.jsx
> put VisibilitySensor on whole Message

- CHANGELOG.md
- devtools/api-mock/participants/data.json
- src/frontend/web_application/src/modules/draftMessage/components/RecipientList/presenter.jsx
- src/frontend/web_application/src/modules/draftMessage/services/isValidRecipient.js
> use protocol from suggestions instead of hardcoded "email"

- CHANGELOG.md
- src/frontend/web_application/src/components/index.js
- src/frontend/web_application/src/scenes/Contact/components/ContactProfileForm/presenter.jsx
- src/frontend/web_application/src/scenes/Contact/components/ContactTitleField/presenter.jsx
- src/frontend/web_application/src/scenes/RemoteIdentitySettings/components/ProviderButton/index.jsx
+ fix click contact's title saves an empty contact
> use RawButton to make sure the button's type is defined

- CHANGELOG.md
- src/frontend/web_application/src/scenes/ContactBook/components/ContactList/presenter.jsx
it shows at least user's contact
> fix empty contact book

- CHANGELOG.md
- src/frontend/web_application/server/auth/router/signin.js
- src/frontend/web_application/src/App.jsx
- src/frontend/web_application/src/modules/notification/components/NotificationProvider/presenter.jsx
- src/frontend/web_application/src/modules/notification/services/notification.worker.js
- src/frontend/web_application/src/modules/routing/services/signout.js
- src/frontend/web_application/src/modules/settings/components/WithSettings/presenter.jsx
- src/frontend/web_application/src/store/middlewares/axios-middleware.js
+ automatic signout if err 401 is caught
+ populate redirect after signout
+ fix request settings until the user is requiring an authenticated page
> handle lost authentication, redirect signin

- CHANGELOG.md
- src/frontend/web_application/src/layouts/Settings/presenter.jsx
- src/frontend/web_application/src/layouts/User/presenter.jsx
- src/frontend/web_application/src/layouts/User/styles.scss
- src/frontend/web_application/src/modules/routing/components/RoutingProvider.jsx
+ add background to user layout
> change link external accounts to user menu

- CHANGELOG.md
- src/frontend/web_application/src/modules/draftMessage/services/filterIdentities.js
- src/frontend/web_application/src/modules/draftMessage/services/filterIdentities.spec.js
+ fix messages protocol only when only one contact but multiples participants
> fix filterIdentities when contacts not yet loaded

- CHANGELOG.md
- src/frontend/web_application/src/scenes/Discussion/components/DownloadFileProgression/index.jsx
- src/frontend/web_application/src/scenes/Discussion/components/MessageAttachments/index.jsx
> add progressbar & and fix download attachments

- CHANGELOG.md
- src/frontend/web_application/src/scenes/DevicesSettings/components/DeviceForm/presenter.jsx
+ refactor anti-pattern generateStateFromProps
> comment locations on device form

- src/frontend/web_application/src/components/Dropdown/index.jsx
- src/frontend/web_application/src/components/DropdownMenu/index.jsx
- src/frontend/web_application/src/modules/draftMessage/components/RecipientList/style.scss
- src/frontend/web_application/src/modules/tags/components/TagFieldGroup/index.jsx
- src/frontend/web_application/src/modules/tags/components/TagsForm/presenter.jsx
- src/frontend/web_application/src/modules/tags/components/TagsForm/presenter.spec.jsx
- src/frontend/web_application/src/modules/tags/components/TagsForm/style.scss
- src/frontend/web_application/src/modules/user/components/UserMenu/presenter.jsx
- src/frontend/web_application/src/scenes/DevicesSettings/components/DeviceForm/presenter.spec.jsx
refactor a bit dropdown
+ eventual solution to calc position when no control ref
+ fix text align for next features buttons
> fix position of tags' dropdown

- src/frontend/web_application/src/modules/encryption/components/AskPassphraseForm/index.jsx
- src/frontend/web_application/src/scenes/UserSecurity/components/OpenPGPKey/presenter.jsx
- src/frontend/web_application/src/services/encryption/index.js
- src/frontend/web_application/src/services/encryption/index.spec.js
Correct encryption detection.
Display uppercase fingerprints.
> Fix encryption check

- CONTRIBUTING.md
- devtools/make_release
- doc/release/README.md
- doc/release/deploy_kubernetes.md
- doc/welcome.md
+ update contributing doc, add welcome.md
+ fix bin/env path
> improve release doc

- CHANGELOG.md
- src/frontend/web_application/src/scenes/Discussion/components/MessageList/presenter.jsx
- src/frontend/web_application/test/functional/features/20-message-list-spec.js
"Load more" was always displayed on discussion tab.
> Hide "load more" on dicussion when all messages are displayed.

- CHANGELOG.md
- src/frontend/web_application/src/modules/encryption/components/LockedMessage/index.jsx
- src/frontend/web_application/src/scenes/Discussion/components/InstantMessage/index.jsx
- src/frontend/web_application/src/scenes/Discussion/components/MailMessage/index.jsx
- src/frontend/web_application/src/scenes/Timeline/components/DiscussionItem/index.jsx
Displays exception's errors message.
> Display decryption error message

- src/frontend/web_application/src/modules/message/components/ParticipantLabel/presenter.jsx
- src/frontend/web_application/src/scenes/Discussion/components/MailMessage/index.jsx
Fixed empty display names on Timeline & message author.
> Fix contact diplay & BSOD

- CHANGELOG.md
- src/frontend/web_application/locale/en/messages.json
- src/frontend/web_application/locale/fr/messages.json
- src/frontend/web_application/src/scenes/Contact/components/IdentityForm/index.jsx
- src/frontend/web_application/src/scenes/ContactBook/components/ContactItem/presenter.jsx
+ remove reference to "@" in twitter input placeholder that is useless on caliopen
> bad attribut was used to display twitter nickname

- src/backend/main/go.backends/store/cassandra/discussions_test.go
- src/backend/main/go.backends/store/cassandra/messages.go
> Fix typo in contact's CleanupLookups

- CHANGELOG.md
- src/frontend/web_application/server/ssr/ssr-middleware.js
- src/frontend/web_application/src/scenes/ContactBook/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/DiscussionItem/index.jsx
- Show at least 1 participant in Timeline. (Fixes #1307)
- Disables contact import. (#1317)
To be continued…
> Several frontend bug fixes.

- CHANGELOG.md
- src/frontend/web_application/server/ssr/ssr-middleware.js
This reverts change of env-var.
> Revert "Display accurate domain in titlebar and signup"

- src/backend/main/go.main/facilities/REST/contacts.go
fix for issues #1295 and #1308
> Prevent to add remote identity to contact if exists

- CHANGELOG.md
- src/frontend/web_application/src/modules/contact/index.js
- src/frontend/web_application/src/modules/contact/services/identityTypes.js
- src/frontend/web_application/src/modules/draftMessage/actions/requestDraft.spec.js
- src/frontend/web_application/src/scenes/Contact/components/FormCollection/index.jsx
- src/frontend/web_application/src/scenes/Contact/components/IdentityForm/index.jsx
- src/frontend/web_application/src/scenes/Contact/index.js
- src/frontend/web_application/src/scenes/Contact/presenter.jsx
- src/frontend/web_application/src/scenes/Contact/services/contactValidation.jsx
- src/frontend/web_application/src/scenes/Contact/services/contactValidation.spec.jsx
- src/frontend/web_application/src/services/renderReduxField/index.jsx
- validation of twitter username
> Contact validation

- src/frontend/web_application/src/modules/message/actions/deleteMessage.js
- src/frontend/web_application/src/scenes/ContactAssociation/presenter.jsx
- src/frontend/web_application/src/scenes/Timeline/components/DiscussionItem/index.jsx
- src/frontend/web_application/src/scenes/UserSecurity/components/OpenPGPKeyForm/index.jsx
- ~Contact should not appear in contact book.~ Can't reproduce anymore. Fixed by backend changes ?
Bonus : 
> Refresh contact & discussion when deletion

- CHANGELOG.md
- src/frontend/web_application/src/modules/draftMessage/components/DraftMessage/presenter.jsx
+ handle «enter» pressed key
+ display spinner when submitting
change quick draft button to a html form
+ handle «enter» pressed key
+ display spinner when submitting
> change quick draft button to a html form

- src/frontend/web_application/src/modules/draftMessage/components/DraftMessage/presenter.jsx
- src/frontend/web_application/src/modules/draftMessage/components/RecipientSelector/presenter.jsx
- src/frontend/web_application/src/modules/draftMessage/services/filterIdentities.js
> handle message participants w/deleted contact

- src/frontend/web_application/src/scenes/ContactBook/presenter.jsx
Replaced `<Plural>` component which do not seem to work properly, with `<Trans>`.
Text is now properly translated in dev env, hopefully it will not crash anymore in dev env.
> (Attempt to) fix BSOD on delete contact.

- CHANGELOG.md
- src/backend/interfaces/NATS/py.client/caliopen_nats/delivery.py
- src/backend/main/py.main/caliopen_main/message/parsers/mail.py
> Some fixes related to invalid data or encoding in incoming mails

- CHANGELOG.md
- src/frontend/web_application/src/modules/draftMessage/actions/consolidateParticipants.js
- src/frontend/web_application/src/modules/draftMessage/actions/saveDraft.js
- src/frontend/web_application/src/modules/encryption/components/AskPassphraseForm/index.jsx
- src/frontend/web_application/src/modules/encryption/components/AskPassphraseForm/style.scss
- src/frontend/web_application/src/scenes/UserSecurity/components/OpenPGPKeyForm/index.jsx
- src/frontend/web_application/src/store/modules/contact.js
**NEEDS #1362**
While creating a new message, check all participants and add contact when it is missing, but available. Thus ensure encryption will not fail due to missing contact reference.
> Contact consolidation

- CHANGELOG.md
- src/frontend/web_application/locale/de/messages.json
- src/frontend/web_application/locale/en/messages.json
- src/frontend/web_application/locale/es/messages.json
- src/frontend/web_application/locale/fr/messages.json
- src/frontend/web_application/src/components/InputFile/index.jsx
- src/frontend/web_application/src/modules/file/index.js
- src/frontend/web_application/src/modules/file/services/index.js
- src/frontend/web_application/src/scenes/Contact/components/PublicKeyForm/presenter.jsx
- src/frontend/web_application/src/scenes/Contact/components/PublicKeyList/presenter.jsx
- src/frontend/web_application/src/scenes/Contact/components/ReduxedInputFileGroup/index.jsx
- src/frontend/web_application/src/scenes/Contact/components/ReduxedInputFileGroup/style.scss
- src/frontend/web_application/src/scenes/UserSecurity/components/OpenPGPKeyForm/index.jsx
Accept files instead of textarea to add/download PGP keys.
> PGP key as file

- CHANGELOG.md
- src/frontend/web_application/src/modules/device/hoc/withDevices/index.jsx
- src/frontend/web_application/src/scenes/DevicesSettings/index.js
- src/frontend/web_application/src/scenes/DevicesSettings/presenter.jsx
> reload devices when invalidated or changing page

- src/frontend/web_application/src/components/AppLoader/index.jsx
More wait messages to add variety.
> Adding more wait messages

- doc/specifications/notification/API-fr.md
- src/frontend/web_application/src/modules/notification/actions/requestNewMessages.js
- src/frontend/web_application/src/modules/notification/components/MessageNotificationHandler/index.js
- src/frontend/web_application/src/modules/notification/components/MessageNotificationHandler/presenter.jsx
- src/frontend/web_application/src/modules/notification/components/NotificationProvider/index.js
- src/frontend/web_application/src/modules/notification/components/NotificationProvider/presenter.jsx
- src/frontend/web_application/src/modules/notification/selectors/messageNotificationsSelector.js
- src/frontend/web_application/src/modules/notification/services/notification.worker.js
- src/frontend/web_application/src/store/modules/notification.js
+ restart notif poller if it has been stoped
+ only invalidate collections instead of fetching all new messages
+ filter notif by last received notif id
fix #1433
> handle new notif api config

- CHANGELOG.md
- src/frontend/web_application/src/modules/user/components/SigninForm/presenter.jsx
+ fix spinner when activity
fix #1452
> [front] use errors in state in signin form

- src/backend/tools/py.CLI/caliopen_cli/commands/resync_shard_index.py
found by lgtm:
https://lgtm.com/projects/g/CaliOpen/Caliopen/overview/https://lgtm.com/projects/g/CaliOpen/Caliopen/overview/
> fix format arguments

- CHANGELOG.md
- src/frontend/web_application/src/modules/draftMessage/services/validate.ts
- src/frontend/web_application/src/scenes/Discussion/components/QuickDraftForm/index.tsx
- add an option to validator to disable body validation
> [frontend] fix quick reply to a dm twitter or mastodon
